ADD	I need more {apples|item}
ADD	I need {one|quantity} more {apples|item}
ADD	I need some more {apples|item}
ADD	I'm out of {apples|item}
ADD	I need {apples|item}
ADD	add {apples|item}
ADD	add {apples|item} to list
ADD	add {one|quantity} {apple|item} to list
QUERY	how many {apples|item} do I need
QUERY	how many {apples|item}
QUERY	{apples|item}
QUERYALL	what's my list look like
QUERYALL	what's on my list
QUERYALL	show list
QUERYALL	tell me what's on my list
DELETE	I got {apples|item}
DELETE	I got {one|quantity} {apple|item}
DELETE	take {apples|item} off list
DELETE	take {apples|item} off my list
DELETE	I don't need {apples|item}
DELETE	I don't need {apples|item} anymore
DELETEALL	I got everything
DELETEALL	start over
DELETEALL	delete list
DELETEALL	clear list
DELETEALL	empty list
SYNCHRONIZE	synchronize
SYNCHRONIZE	sync
SEND	send list
SEND	send
SEND	send me my list
SEND	email list
SEND	mail me
SEND	mail