NUMBERS	{one|firstDigit} {zulu|secondDigit} {zero|thirdDigit}
NUMBERS	{zero|firstDigit} {nine|secondDigit} {four|thirdDigit}
NUMBERS	{one|firstDigit} {one|secondDigit} {alpha|thirdDigit}
NUMBERS	{eight|firstDigit} {six|secondDigit} {three|thirdDigit}
NUMBERS	{eight|firstDigit} {one|secondDigit} {five|thirdDigit}
NUMBERS	{five|firstDigit} {two|secondDigit} {three|thirdDigit}
NUMBERS	{one|firstDigit} {zulu|secondDigit} {echo|thirdDigit}
NUMBERS	{three|firstDigit} {three|secondDigit} {four|thirdDigit}
NUMBERS	{waldo|firstDigit} {two|secondDigit} {three|thirdDigit}
NUMBERS	{nine|firstDigit} {four|secondDigit} {zero|thirdDigit}
NUMBERS	{zero|firstDigit} {six|secondDigit} {two|thirdDigit}
NUMBERS	{nine|firstDigit} {one|secondDigit} {one|thirdDigit}
NUMBERS	{one|firstDigit} {zulu|secondDigit} {one|thirdDigit}
NUMBERS	{two|firstDigit} {three|secondDigit} {four|thirdDigit}
NUMBERS	{five|firstDigit} {echo|secondDigit} {zero|thirdDigit}
NUMBERS	{two|firstDigit} {nine|secondDigit} {one|thirdDigit}
NUMBERS	{nine|firstDigit} {eight|secondDigit} {zero|thirdDigit}
NUMBERS	{seven|firstDigit} {nine|secondDigit} {three|thirdDigit}
NUMBER	{one|firstDigit}
NUMBER	{two|firstDigit}
NUMBER	{three|firstDigit}
NUMBER	{four|firstDigit}
NUMBER	{five|firstDigit}
NUMBER	{six|firstDigit}
NUMBER	{seven|firstDigit}
NUMBER	{eight|firstDigit}
STATUS	status
STATUS	update
STATUS	check status
STATUS	when
STATUS	when are my packages coming
ADD	add
ADD	track
ADD	track package
ADD	add package
ADD	new package
ADD	add new package
REMOVE	remove
REMOVE	delete
REMOVE	stop tracking
YES	yes
YES	yep
YES	afirmative
YES	correct
NO	no
NO	nope
NO	wrong
ABORT	abort
ABORT	cancel
ABORT	stop
CLEAR	delete all
CLEAR	clear
CLEAR	reset
HELP	help
LIST	list
LIST	what am i tracking
 