//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.20 at 10:17:54 AM EDT 
//


package com.ups.xolt.codesamples.request.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}Request"/&gt;
 *         &lt;choice&gt;
 *           &lt;element ref="{}TrackingNumber"/&gt;
 *           &lt;element ref="{}ShipmentIdentificationNumber"/&gt;
 *           &lt;element ref="{}CandidateBookmark"/&gt;
 *           &lt;sequence&gt;
 *             &lt;element ref="{}ReferenceNumber"/&gt;
 *             &lt;element ref="{}PickupDateRange" minOccurs="0"/&gt;
 *             &lt;element ref="{}ShipperNumber" minOccurs="0"/&gt;
 *             &lt;element ref="{}DestinationPostalCode" minOccurs="0"/&gt;
 *             &lt;element ref="{}DestinationCountryCode" minOccurs="0"/&gt;
 *             &lt;element ref="{}OriginPostalCode" minOccurs="0"/&gt;
 *             &lt;element ref="{}OriginCountryCode" minOccurs="0"/&gt;
 *             &lt;element name="ShipmentType" type="{}CodeType" minOccurs="0"/&gt;
 *           &lt;/sequence&gt;
 *         &lt;/choice&gt;
 *         &lt;element name="TrackingOption" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="UPSWorldWideExpressFreightShipment" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element ref="{}IncludeFreight" minOccurs="0"/&gt;
 *         &lt;element ref="{}ShipperAccountInfo" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "request",
    "trackingNumber",
    "shipmentIdentificationNumber",
    "candidateBookmark",
    "referenceNumber",
    "pickupDateRange",
    "shipperNumber",
    "destinationPostalCode",
    "destinationCountryCode",
    "originPostalCode",
    "originCountryCode",
    "shipmentType",
    "trackingOption",
    "upsWorldWideExpressFreightShipment",
    "includeFreight",
    "shipperAccountInfo"
})
@XmlRootElement(name = "TrackRequest")
public class TrackRequest {

    @XmlElement(name = "Request", required = true)
    protected Request request;
    @XmlElement(name = "TrackingNumber")
    protected String trackingNumber;
    @XmlElement(name = "ShipmentIdentificationNumber")
    protected String shipmentIdentificationNumber;
    @XmlElement(name = "CandidateBookmark")
    protected String candidateBookmark;
    @XmlElement(name = "ReferenceNumber")
    protected ReferenceNumber referenceNumber;
    @XmlElement(name = "PickupDateRange")
    protected PickupDateRange pickupDateRange;
    @XmlElement(name = "ShipperNumber")
    protected String shipperNumber;
    @XmlElement(name = "DestinationPostalCode")
    protected String destinationPostalCode;
    @XmlElement(name = "DestinationCountryCode")
    protected String destinationCountryCode;
    @XmlElement(name = "OriginPostalCode")
    protected String originPostalCode;
    @XmlElement(name = "OriginCountryCode")
    protected String originCountryCode;
    @XmlElement(name = "ShipmentType")
    protected CodeType shipmentType;
    @XmlElement(name = "TrackingOption")
    protected String trackingOption;
    @XmlElement(name = "UPSWorldWideExpressFreightShipment")
    protected String upsWorldWideExpressFreightShipment;
    @XmlElement(name = "IncludeFreight")
    protected String includeFreight;
    @XmlElement(name = "ShipperAccountInfo")
    protected ShipperAccountInfo shipperAccountInfo;

    /**
     * Gets the value of the request property.
     * 
     * @return
     *     possible object is
     *     {@link Request }
     *     
     */
    public Request getRequest() {
        return request;
    }

    /**
     * Sets the value of the request property.
     * 
     * @param value
     *     allowed object is
     *     {@link Request }
     *     
     */
    public void setRequest(Request value) {
        this.request = value;
    }

    /**
     * Gets the value of the trackingNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrackingNumber() {
        return trackingNumber;
    }

    /**
     * Sets the value of the trackingNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrackingNumber(String value) {
        this.trackingNumber = value;
    }

    /**
     * Gets the value of the shipmentIdentificationNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipmentIdentificationNumber() {
        return shipmentIdentificationNumber;
    }

    /**
     * Sets the value of the shipmentIdentificationNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipmentIdentificationNumber(String value) {
        this.shipmentIdentificationNumber = value;
    }

    /**
     * Gets the value of the candidateBookmark property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCandidateBookmark() {
        return candidateBookmark;
    }

    /**
     * Sets the value of the candidateBookmark property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCandidateBookmark(String value) {
        this.candidateBookmark = value;
    }

    /**
     * Gets the value of the referenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link ReferenceNumber }
     *     
     */
    public ReferenceNumber getReferenceNumber() {
        return referenceNumber;
    }

    /**
     * Sets the value of the referenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferenceNumber }
     *     
     */
    public void setReferenceNumber(ReferenceNumber value) {
        this.referenceNumber = value;
    }

    /**
     * Gets the value of the pickupDateRange property.
     * 
     * @return
     *     possible object is
     *     {@link PickupDateRange }
     *     
     */
    public PickupDateRange getPickupDateRange() {
        return pickupDateRange;
    }

    /**
     * Sets the value of the pickupDateRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link PickupDateRange }
     *     
     */
    public void setPickupDateRange(PickupDateRange value) {
        this.pickupDateRange = value;
    }

    /**
     * Gets the value of the shipperNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipperNumber() {
        return shipperNumber;
    }

    /**
     * Sets the value of the shipperNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipperNumber(String value) {
        this.shipperNumber = value;
    }

    /**
     * Gets the value of the destinationPostalCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestinationPostalCode() {
        return destinationPostalCode;
    }

    /**
     * Sets the value of the destinationPostalCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestinationPostalCode(String value) {
        this.destinationPostalCode = value;
    }

    /**
     * Gets the value of the destinationCountryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestinationCountryCode() {
        return destinationCountryCode;
    }

    /**
     * Sets the value of the destinationCountryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestinationCountryCode(String value) {
        this.destinationCountryCode = value;
    }

    /**
     * Gets the value of the originPostalCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginPostalCode() {
        return originPostalCode;
    }

    /**
     * Sets the value of the originPostalCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginPostalCode(String value) {
        this.originPostalCode = value;
    }

    /**
     * Gets the value of the originCountryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginCountryCode() {
        return originCountryCode;
    }

    /**
     * Sets the value of the originCountryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginCountryCode(String value) {
        this.originCountryCode = value;
    }

    /**
     * Gets the value of the shipmentType property.
     * 
     * @return
     *     possible object is
     *     {@link CodeType }
     *     
     */
    public CodeType getShipmentType() {
        return shipmentType;
    }

    /**
     * Sets the value of the shipmentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeType }
     *     
     */
    public void setShipmentType(CodeType value) {
        this.shipmentType = value;
    }

    /**
     * Gets the value of the trackingOption property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrackingOption() {
        return trackingOption;
    }

    /**
     * Sets the value of the trackingOption property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrackingOption(String value) {
        this.trackingOption = value;
    }

    /**
     * Gets the value of the upsWorldWideExpressFreightShipment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUPSWorldWideExpressFreightShipment() {
        return upsWorldWideExpressFreightShipment;
    }

    /**
     * Sets the value of the upsWorldWideExpressFreightShipment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUPSWorldWideExpressFreightShipment(String value) {
        this.upsWorldWideExpressFreightShipment = value;
    }

    /**
     * Gets the value of the includeFreight property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIncludeFreight() {
        return includeFreight;
    }

    /**
     * Sets the value of the includeFreight property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIncludeFreight(String value) {
        this.includeFreight = value;
    }

    /**
     * Gets the value of the shipperAccountInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ShipperAccountInfo }
     *     
     */
    public ShipperAccountInfo getShipperAccountInfo() {
        return shipperAccountInfo;
    }

    /**
     * Sets the value of the shipperAccountInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShipperAccountInfo }
     *     
     */
    public void setShipperAccountInfo(ShipperAccountInfo value) {
        this.shipperAccountInfo = value;
    }

}
