RESPONSE	cd who?
RESPONSE	dishes who?
RESPONSE	scold who?
RESPONSE	ketchup who?
RESPONSE	abby who?
RESPONSE	etch who?
RESPONSE	king tut who?
RESPONSE	iona who?
RESPONSE	arfur who?
RESPONSE	who’s there?
RESPONSE	cows go who?
RESPONSE	boo who?
RESPONSE	avenue who?
RESPONSE	roach who?
RESPONSE	dwayne who?
RESPONSE	i am who?
RESPONSE	ivor who?
RESPONSE	olive who?
RESPONSE	yes.
RESPONSE	harry who?
RESPONSE	hoo who?
RESPONSE	isabell who?
RESPONSE	nana who?
RESPONSE	robin who?
RESPONSE	orange who?
RESPONSE	imma who?
RESPONSE	aida who?
RESPONSE	lettuce who?
RESPONSE	althea who?
RESPONSE	annie who?
RESPONSE	dozen who?
RESPONSE	noah who?
RESPONSE	viper who?
RESPONSE	luke who?
RESPONSE	henrietta who?
RESPONSE	two knee who?
RESPONSE	ya who?
RESPONSE	abbot who?
RESPONSE	tank who?
RESPONSE	banana who?
RESPONSE	iowa who?
RESPONSE	justin who?
RESPONSE	kirtch who?
RESPONSE	watson who?
RESPONSE	cook who?
RESPONSE	needle who?
RESPONSE	canoe who?
RESPONSE	anee,who?
RESPONSE	sadie who?
RESPONSE	norma lee who?
RESPONSE	ben who?
RESPONSE	spell who?
RESPONSE	adore who?
RESPONSE	alex who?
RESPONSE	iva who?
RESPONSE	claire who?
RESPONSE	a little old lady who?
RESPONSE	a herd who?
RESPONSE	police who?
RESPONSE	otto who?
RESPONSE	merry who?
RESPONSE	impatient cow wh-?
RESPONSE	{anything|anything}
QUIT	done
QUIT	quit
QUIT	exit
QUIT	I'm done
QUIT	go away

