package jo.flash.logic;

import java.util.ArrayList;
import java.util.List;
import java.util.StringTokenizer;

import jo.flash.data.FlashWord;
import jo.flash.data.FlashWordList;

public class WordsLogic
{
    private static List<FlashWordList> mLists = null;
    
    public static int getNumberOfLists()
    {
        return GAME_NAMES.length;
    }
    
    public static FlashWordList getList(int n)
    {
        if (mLists == null)
        {
            mLists = new ArrayList<FlashWordList>();
            for (int i = 0; i < GAME_NAMES.length; i++)
            {
                FlashWordList list = new FlashWordList();
                list.setName(GAME_NAMES[i]);
                for (String wordSpec : WORD_LISTS[i])
                {
                    StringTokenizer names = new StringTokenizer(wordSpec, "|");
                    FlashWord word = new FlashWord();
                    word.setWord(names.nextToken());
                    if (!names.hasMoreTokens())
                        word.getNames().add(word.getWord());
                    else
                        while (names.hasMoreTokens())
                            word.getNames().add(names.nextToken());
                    list.getWords().add(word);
                }
                mLists.add(list);
            }
        }
        return mLists.get(n);
    }
    
    public static final String[] GAME_NAMES = {
        "Sight Words",
        "Greek Mythology",
        "Norse Mythology",
        "Addition",
    };
    
    public static final String[] SIGHT = {
        "the",
        "and",
        "of ",
        "to",
        "a",
        "was",
        "is",
        "he",
        "for",
        "you",
        "as ",
        "his",
        "has",
        "we",
        "I",
        "they",
        "one",
        "said",
        "from",
        "or",
        "have",
        "were",
        "her",
        "put",
        "there",
        "what",
        "she",
        "been",
        "by",
        "who",
        "out",
        "so",
        "are",
        "two",
        "about",
        "into",
        "only",
        "new",
        "other",
        "some",
        "could",
        "say",
        "want",
        "do",
        "first",
        "any",
        "my",
        "now",
        "our",
        "over",
        "come",
        "after",
        "would",
        "many",
        "also",
        "before",
        "called",
        "how",
        "your",
        "down",
        "should",
        "because",
        "people",
        "Mr.",
        "each",
        "years",
        "Mrs.",
        "says",
        "little",
        "good",
        "very",
        "own",
        "see",
        "work",
        "between",
        "both",
        "being",
        "under",
        "never",
        "day",
        "another",
        "words",
        "look",
        "through",
        "friend",
        "around",
        "circle",
        "does",
        "nothing",
        "write",
        "none",
        "color",
         "month",  
    };
    
    public static final String[] GREEK = {
        "Aphrodite",
        "Apollo",
        "Ares",
        "Artemis",
        "Athena",
        "Demeter",
        "Dionysus",
        "Hades",
        "Hephaestus",
        "Hera",
        "Hermes ",
        "Hestia",
        "Poseidon",
        "Zeus",
        "Chronos",
        "Uranus",
        "Gaia",
        "Rhea",
        "Tarterus",
        "Atlas",
        "Prometheus",
        "Achilles",
        "Heracles",
        "Hector",
        "Jason",
        "Odysseus",
        "Orpheus",
        "Theseus",
        "Andromeda",
        "Helen",
        "Medusa",
        "Hippolyta",
        "Jupiter",
        "Juno",
        "Neptune",
        "Minerva",
        "Mars",
        "Venus",
        "Apollo",
        "Diana",
        "Vulcan",
        "Vesta",
        "Mercury",
        "Ceres",
        "Α|alpha",
        "Β|beta",
        "Γ|gamma",
        "Δ|delta",
        "Ε|epsilon",
        "Ζ|zeta",
        "Η|eta",
        "Θ|theta",
        "Ι|iota",
        "Κ|kappa",
        "Λ|lambda",
        "Μ|mu",
        "Ν|nu",
        "Ξ|xi",
        "Ο|omicron",
        "Π|pi",
        "Ρ|rho",
        "Σ|sigma",
        "Τ|tau",
        "Υ|upsilon",
        "Φ|phi",
        "Χ|chi",
        "Ψ|psi",
        "Ω|omega",
        "α|alpha",
        "β|beta",
        "γ|gamma",
        "δ|delta",
        "ε|epsilon",
        "ζ|zeta",
        "η|eta",
        "θ|theta",
        "ι|iota",
        "κ|kappa",
        "λ|lambda",
        "μ|mu",
        "ν|nu",
        "ξ|xi",
        "ο|omicron",
        "π|pi",
        "ρ|rho",
        "σ|sigma",
        "τ|tau",
        "υ|upsilon",
        "φ|phi",
        "χ|chi",
        "ψ|psi",
        "ω|omega",  
    };
    
    public static final String[] NORSE = {
        "ᚠ|fehu",
        "ᚢ|uruz",
        "ᚦ|thurisaz",
        "ᚨ|ansuz",
        "ᚱ|radio",
        "ᚲ|kaunan",
        "ᚷ|gebo",
        "ᚹ|wunjo",
        "ᚺ|hagalaz",
        "ᚾ|naudiz",
        "ᛁ|isaz",
        "ᛃ|jera",
        "ᛇ|waz",
        "ᛈ|perth",
        "ᛉ|algiz",
        "ᛊ|sowilo",
        "ᛏ|tiwaz",
        "ᛒ|berkanan",
        "ᛖ|ehwaz",
        "ᛗ|mannaz",
        "ᛚ|laguz",
        "ᛝ|ingwaz",
        "ᛟ|othila",
        "ᛞ|dagaz",
        "Baldr",
        "Freyr",
        "Heimdallr",
        "Loki",
        "Odin",
        "Thor",
        "Týr|Tyr",
        "Ullr",
        "Freyja",
        "Frigg",
        "Sif",  
    };
    
    public static final String[] ADDITION = {
        "1 + 1|two",
        "1 + 2|three",
        "1 + 3|four",
        "1 + 4|five",
        "1 + 5|six",
        "1 + 6|seven",
        "1 + 7|eight",
        "1 + 8|nine",
        "1 + 9|ten",
        "1 + 10|eleven",
        "2 + 1|three",
        "2 + 2|four",
        "2 + 3|five",
        "2 + 4|six",
        "2 + 5|seven",
        "2 + 6|eight",
        "2 + 7|nine",
        "2 + 8|ten",
        "2 + 9|eleven",
        "2 + 10|twelve",
        "3 + 1|four",
        "3 + 2|five",
        "3 + 3|six",
        "3 + 4|seven",
        "3 + 5|eight",
        "3 + 6|nine",
        "3 + 7|ten",
        "3 + 8|eleven",
        "3 + 9|twelve",
        "3 + 10|thirteen",
        "4 + 1|five",
        "4 + 2|six",
        "4 + 3|seven",
        "4 + 4|eight",
        "4 + 5|nine",
        "4 + 6|ten",
        "4 + 7|eleven",
        "4 + 8|twelve",
        "4 + 9|thirteen",
        "4 + 10|fourteen",
        "5 + 1|six",
        "5 + 2|seven",
        "5 + 3|eight",
        "5 + 4|nine",
        "5 + 5|ten",
        "5 + 6|eleven",
        "5 + 7|twelve",
        "5 + 8|thirteen",
        "5 + 9|fourteen",
        "5 + 10|fifteen",
        "6 + 1|seven",
        "6 + 2|eight",
        "6 + 3|nine",
        "6 + 4|ten",
        "6 + 5|eleven",
        "6 + 6|twelve",
        "6 + 7|thirteen",
        "6 + 8|fourteen",
        "6 + 9|fifteen",
        "6 + 10|sixteen",
        "7 + 1|eight",
        "7 + 2|nine",
        "7 + 3|ten",
        "7 + 4|eleven",
        "7 + 5|twelve",
        "7 + 6|thirteen",
        "7 + 7|fourteen",
        "7 + 8|fifteen",
        "7 + 9|sixteen",
        "7 + 10|seventeen",
        "8 + 1|nine",
        "8 + 2|ten",
        "8 + 3|eleven",
        "8 + 4|twelve",
        "8 + 5|thirteen",
        "8 + 6|fourteen",
        "8 + 7|fifteen",
        "8 + 8|sixteen",
        "8 + 9|seventeen",
        "8 + 10|eighteen",
        "9 + 1|ten",
        "9 + 2|eleven",
        "9 + 3|twelve",
        "9 + 4|thirteen",
        "9 + 5|fourteen",
        "9 + 6|fifteen",
        "9 + 7|sixteen",
        "9 + 8|seventeen",
        "9 + 9|eighteen",
        "9 + 10|nineteen",
        "10 + 1|eleven",
        "10 + 2|twelve",
        "10 + 3|thirteen",
        "10 + 4|fourteen",
        "10 + 5|fifteen",
        "10 + 6|sixteen",
        "10 + 7|seventeen",
        "10 + 8|eighteen",
        "10 + 9|nineteen",
        "10 + 10|twenty",
    };
    
    public static final String[][] WORD_LISTS = {
        SIGHT,
        GREEK,
        NORSE,
        ADDITION,
    };
}
