NORTH	north
NORTH	go north
SOUTH	south
SOUTH	go south
EAST	east
EAST	go east
WEST	west
WEST	go west
NORTHWEST	north west
NORTHWEST	go north west
NORTHWEST	northwest
NORTHWEST	go northwest
SOUTHWEST	south west
SOUTHWEST	go south west
SOUTHWEST	southwest
SOUTHWEST	go southwest
NORTHEAST	north east
NORTHEAST	go north east
NORTHEAST	northeast
NORTHEAST	go northeast
SOUTHEAST	south east
SOUTHEAST	go south east
SOUTHEAST	southeast
SOUTHEAST	go southeast
UP	up
UP	go up
DOWN	down
DOWN	go down
UP	climb up
DOWN	climb down
LOOK	look
UNLOCK	unlock {cage|directObject} with {keys|indirectObject}
UNLOCK	unlock {chain|directObject} with {keys|indirectObject}
UNLOCK	unlock {grate|directObject} with {keys|indirectObject}
UNLOCK	unlock {door|directObject} with {keys|indirectObject}
POUR	pour {water|directObject} on {sliver|indirectObject}
POUR	pour {water|directObject} on {bars|indirectObject}
POUR	pour {water|directObject} on {silver bars|indirectObject}
POUR	pour {water|directObject} on {all|indirectObject}
POUR	pour {water|directObject} on {bird|indirectObject}
POUR	pour {water|directObject} on {cage|indirectObject}
POUR	pour {water|directObject} on {wicker cage|indirectObject}
POUR	pour {water|directObject} on {gold nugget|indirectObject}
POUR	pour {water|directObject} on {nugget|indirectObject}
POUR	pour {water|directObject} on {keys|indirectObject}
POUR	pour {water|directObject} on {food|indirectObject}
POUR	pour {water|directObject} on {lamp|indirectObject}
POUR	pour {water|directObject} on {grate|indirectObject}
POUR	pour {water|directObject} on {dragon|indirectObject}
POUR	pour {water|directObject} on {rug|indirectObject}
POUR	pour {water|directObject} on {persian rug|indirectObject}
POUR	pour {water|directObject} on {water|indirectObject}
POUR	pour {water|directObject} on {plant|indirectObject}
POUR	pour {water|directObject} on {emerald|indirectObject}
POUR	pour {water|directObject} on {vase|indirectObject}
POUR	pour {water|directObject} on {ming vase|indirectObject}
POUR	pour {water|directObject} on {pillow|indirectObject}
POUR	pour {water|directObject} on {pyramid|indirectObject}
POUR	pour {water|directObject} on {beanstalk|indirectObject}
POUR	pour {water|directObject} on {eggs|indirectObject}
POUR	pour {water|directObject} on {door|indirectObject}
POUR	pour {water|directObject} on {trident|indirectObject}
POUR	pour {water|directObject} on {bear|indirectObject}
POUR	pour {water|directObject} on {troll|indirectObject}
POUR	pour {water|directObject} on {chain|indirectObject}
POUR	pour {water|directObject} on {spices|indirectObject}
POUR	pour {water|directObject} on {magazine|indirectObject}
POUR	pour {water|directObject} on {pearl|indirectObject}
POUR	pour {water|directObject} on {jewelry|indirectObject}
POUR	pour {water|directObject} on {coins|indirectObject}
POUR	pour {water|directObject} on {diamonds|indirectObject}
POUR	pour {water|directObject} on {rod|indirectObject}
POUR	pour {water|directObject} on {axe|indirectObject}
POUR	pour {water|directObject} on {dwarf|indirectObject}
GIVE	give {sliver|directObject} to {sliver|indirectObject}
GIVE	give {sliver|directObject} to {bars|indirectObject}
GIVE	give {sliver|directObject} to {silver bars|indirectObject}
GIVE	give {sliver|directObject} to {all|indirectObject}
GIVE	give {sliver|directObject} to {bird|indirectObject}
GIVE	give {sliver|directObject} to {cage|indirectObject}
GIVE	give {sliver|directObject} to {wicker cage|indirectObject}
GIVE	give {sliver|directObject} to {gold nugget|indirectObject}
GIVE	give {sliver|directObject} to {nugget|indirectObject}
GIVE	give {sliver|directObject} to {keys|indirectObject}
GIVE	give {sliver|directObject} to {food|indirectObject}
GIVE	give {sliver|directObject} to {lamp|indirectObject}
GIVE	give {sliver|directObject} to {grate|indirectObject}
GIVE	give {sliver|directObject} to {dragon|indirectObject}
GIVE	give {sliver|directObject} to {rug|indirectObject}
GIVE	give {sliver|directObject} to {persian rug|indirectObject}
GIVE	give {sliver|directObject} to {water|indirectObject}
GIVE	give {sliver|directObject} to {plant|indirectObject}
GIVE	give {sliver|directObject} to {emerald|indirectObject}
GIVE	give {sliver|directObject} to {vase|indirectObject}
GIVE	give {sliver|directObject} to {ming vase|indirectObject}
GIVE	give {sliver|directObject} to {pillow|indirectObject}
GIVE	give {sliver|directObject} to {pyramid|indirectObject}
GIVE	give {sliver|directObject} to {beanstalk|indirectObject}
GIVE	give {sliver|directObject} to {eggs|indirectObject}
GIVE	give {sliver|directObject} to {door|indirectObject}
GIVE	give {sliver|directObject} to {trident|indirectObject}
GIVE	give {sliver|directObject} to {bear|indirectObject}
GIVE	give {sliver|directObject} to {troll|indirectObject}
GIVE	give {sliver|directObject} to {chain|indirectObject}
GIVE	give {sliver|directObject} to {spices|indirectObject}
GIVE	give {sliver|directObject} to {magazine|indirectObject}
GIVE	give {sliver|directObject} to {pearl|indirectObject}
GIVE	give {sliver|directObject} to {jewelry|indirectObject}
GIVE	give {sliver|directObject} to {coins|indirectObject}
GIVE	give {sliver|directObject} to {diamonds|indirectObject}
GIVE	give {sliver|directObject} to {rod|indirectObject}
GIVE	give {sliver|directObject} to {axe|indirectObject}
GIVE	give {sliver|directObject} to {dwarf|indirectObject}
GIVE	give {bars|directObject} to {sliver|indirectObject}
GIVE	give {bars|directObject} to {bars|indirectObject}
GIVE	give {bars|directObject} to {silver bars|indirectObject}
GIVE	give {bars|directObject} to {all|indirectObject}
GIVE	give {bars|directObject} to {bird|indirectObject}
GIVE	give {bars|directObject} to {cage|indirectObject}
GIVE	give {bars|directObject} to {wicker cage|indirectObject}
GIVE	give {bars|directObject} to {gold nugget|indirectObject}
GIVE	give {bars|directObject} to {nugget|indirectObject}
GIVE	give {bars|directObject} to {keys|indirectObject}
GIVE	give {bars|directObject} to {food|indirectObject}
GIVE	give {bars|directObject} to {lamp|indirectObject}
GIVE	give {bars|directObject} to {grate|indirectObject}
GIVE	give {bars|directObject} to {dragon|indirectObject}
GIVE	give {bars|directObject} to {rug|indirectObject}
GIVE	give {bars|directObject} to {persian rug|indirectObject}
GIVE	give {bars|directObject} to {water|indirectObject}
GIVE	give {bars|directObject} to {plant|indirectObject}
GIVE	give {bars|directObject} to {emerald|indirectObject}
GIVE	give {bars|directObject} to {vase|indirectObject}
GIVE	give {bars|directObject} to {ming vase|indirectObject}
GIVE	give {bars|directObject} to {pillow|indirectObject}
GIVE	give {bars|directObject} to {pyramid|indirectObject}
GIVE	give {bars|directObject} to {beanstalk|indirectObject}
GIVE	give {bars|directObject} to {eggs|indirectObject}
GIVE	give {bars|directObject} to {door|indirectObject}
GIVE	give {bars|directObject} to {trident|indirectObject}
GIVE	give {bars|directObject} to {bear|indirectObject}
GIVE	give {bars|directObject} to {troll|indirectObject}
GIVE	give {bars|directObject} to {chain|indirectObject}
GIVE	give {bars|directObject} to {spices|indirectObject}
GIVE	give {bars|directObject} to {magazine|indirectObject}
GIVE	give {bars|directObject} to {pearl|indirectObject}
GIVE	give {bars|directObject} to {jewelry|indirectObject}
GIVE	give {bars|directObject} to {coins|indirectObject}
GIVE	give {bars|directObject} to {diamonds|indirectObject}
GIVE	give {bars|directObject} to {rod|indirectObject}
GIVE	give {bars|directObject} to {axe|indirectObject}
GIVE	give {bars|directObject} to {dwarf|indirectObject}
GIVE	give {silver bars|directObject} to {sliver|indirectObject}
GIVE	give {silver bars|directObject} to {bars|indirectObject}
GIVE	give {silver bars|directObject} to {silver bars|indirectObject}
GIVE	give {silver bars|directObject} to {all|indirectObject}
GIVE	give {silver bars|directObject} to {bird|indirectObject}
GIVE	give {silver bars|directObject} to {cage|indirectObject}
GIVE	give {silver bars|directObject} to {wicker cage|indirectObject}
GIVE	give {silver bars|directObject} to {gold nugget|indirectObject}
GIVE	give {silver bars|directObject} to {nugget|indirectObject}
GIVE	give {silver bars|directObject} to {keys|indirectObject}
GIVE	give {silver bars|directObject} to {food|indirectObject}
GIVE	give {silver bars|directObject} to {lamp|indirectObject}
GIVE	give {silver bars|directObject} to {grate|indirectObject}
GIVE	give {silver bars|directObject} to {dragon|indirectObject}
GIVE	give {silver bars|directObject} to {rug|indirectObject}
GIVE	give {silver bars|directObject} to {persian rug|indirectObject}
GIVE	give {silver bars|directObject} to {water|indirectObject}
GIVE	give {silver bars|directObject} to {plant|indirectObject}
GIVE	give {silver bars|directObject} to {emerald|indirectObject}
GIVE	give {silver bars|directObject} to {vase|indirectObject}
GIVE	give {silver bars|directObject} to {ming vase|indirectObject}
GIVE	give {silver bars|directObject} to {pillow|indirectObject}
GIVE	give {silver bars|directObject} to {pyramid|indirectObject}
GIVE	give {silver bars|directObject} to {beanstalk|indirectObject}
GIVE	give {silver bars|directObject} to {eggs|indirectObject}
GIVE	give {silver bars|directObject} to {door|indirectObject}
GIVE	give {silver bars|directObject} to {trident|indirectObject}
GIVE	give {silver bars|directObject} to {bear|indirectObject}
GIVE	give {silver bars|directObject} to {troll|indirectObject}
GIVE	give {silver bars|directObject} to {chain|indirectObject}
GIVE	give {silver bars|directObject} to {spices|indirectObject}
GIVE	give {silver bars|directObject} to {magazine|indirectObject}
GIVE	give {silver bars|directObject} to {pearl|indirectObject}
GIVE	give {silver bars|directObject} to {jewelry|indirectObject}
GIVE	give {silver bars|directObject} to {coins|indirectObject}
GIVE	give {silver bars|directObject} to {diamonds|indirectObject}
GIVE	give {silver bars|directObject} to {rod|indirectObject}
GIVE	give {silver bars|directObject} to {axe|indirectObject}
GIVE	give {silver bars|directObject} to {dwarf|indirectObject}
GIVE	give {all|directObject} to {sliver|indirectObject}
GIVE	give {all|directObject} to {bars|indirectObject}
GIVE	give {all|directObject} to {silver bars|indirectObject}
GIVE	give {all|directObject} to {all|indirectObject}
GIVE	give {all|directObject} to {bird|indirectObject}
GIVE	give {all|directObject} to {cage|indirectObject}
GIVE	give {all|directObject} to {wicker cage|indirectObject}
GIVE	give {all|directObject} to {gold nugget|indirectObject}
GIVE	give {all|directObject} to {nugget|indirectObject}
GIVE	give {all|directObject} to {keys|indirectObject}
GIVE	give {all|directObject} to {food|indirectObject}
GIVE	give {all|directObject} to {lamp|indirectObject}
GIVE	give {all|directObject} to {grate|indirectObject}
GIVE	give {all|directObject} to {dragon|indirectObject}
GIVE	give {all|directObject} to {rug|indirectObject}
GIVE	give {all|directObject} to {persian rug|indirectObject}
GIVE	give {all|directObject} to {water|indirectObject}
GIVE	give {all|directObject} to {plant|indirectObject}
GIVE	give {all|directObject} to {emerald|indirectObject}
GIVE	give {all|directObject} to {vase|indirectObject}
GIVE	give {all|directObject} to {ming vase|indirectObject}
GIVE	give {all|directObject} to {pillow|indirectObject}
GIVE	give {all|directObject} to {pyramid|indirectObject}
GIVE	give {all|directObject} to {beanstalk|indirectObject}
GIVE	give {all|directObject} to {eggs|indirectObject}
GIVE	give {all|directObject} to {door|indirectObject}
GIVE	give {all|directObject} to {trident|indirectObject}
GIVE	give {all|directObject} to {bear|indirectObject}
GIVE	give {all|directObject} to {troll|indirectObject}
GIVE	give {all|directObject} to {chain|indirectObject}
GIVE	give {all|directObject} to {spices|indirectObject}
GIVE	give {all|directObject} to {magazine|indirectObject}
GIVE	give {all|directObject} to {pearl|indirectObject}
GIVE	give {all|directObject} to {jewelry|indirectObject}
GIVE	give {all|directObject} to {coins|indirectObject}
GIVE	give {all|directObject} to {diamonds|indirectObject}
GIVE	give {all|directObject} to {rod|indirectObject}
GIVE	give {all|directObject} to {axe|indirectObject}
GIVE	give {all|directObject} to {dwarf|indirectObject}
GIVE	give {bird|directObject} to {sliver|indirectObject}
GIVE	give {bird|directObject} to {bars|indirectObject}
GIVE	give {bird|directObject} to {silver bars|indirectObject}
GIVE	give {bird|directObject} to {all|indirectObject}
GIVE	give {bird|directObject} to {bird|indirectObject}
GIVE	give {bird|directObject} to {cage|indirectObject}
GIVE	give {bird|directObject} to {wicker cage|indirectObject}
GIVE	give {bird|directObject} to {gold nugget|indirectObject}
GIVE	give {bird|directObject} to {nugget|indirectObject}
GIVE	give {bird|directObject} to {keys|indirectObject}
GIVE	give {bird|directObject} to {food|indirectObject}
GIVE	give {bird|directObject} to {lamp|indirectObject}
GIVE	give {bird|directObject} to {grate|indirectObject}
GIVE	give {bird|directObject} to {dragon|indirectObject}
GIVE	give {bird|directObject} to {rug|indirectObject}
GIVE	give {bird|directObject} to {persian rug|indirectObject}
GIVE	give {bird|directObject} to {water|indirectObject}
GIVE	give {bird|directObject} to {plant|indirectObject}
GIVE	give {bird|directObject} to {emerald|indirectObject}
GIVE	give {bird|directObject} to {vase|indirectObject}
GIVE	give {bird|directObject} to {ming vase|indirectObject}
GIVE	give {bird|directObject} to {pillow|indirectObject}
GIVE	give {bird|directObject} to {pyramid|indirectObject}
GIVE	give {bird|directObject} to {beanstalk|indirectObject}
GIVE	give {bird|directObject} to {eggs|indirectObject}
GIVE	give {bird|directObject} to {door|indirectObject}
GIVE	give {bird|directObject} to {trident|indirectObject}
GIVE	give {bird|directObject} to {bear|indirectObject}
GIVE	give {bird|directObject} to {troll|indirectObject}
GIVE	give {bird|directObject} to {chain|indirectObject}
GIVE	give {bird|directObject} to {spices|indirectObject}
GIVE	give {bird|directObject} to {magazine|indirectObject}
GIVE	give {bird|directObject} to {pearl|indirectObject}
GIVE	give {bird|directObject} to {jewelry|indirectObject}
GIVE	give {bird|directObject} to {coins|indirectObject}
GIVE	give {bird|directObject} to {diamonds|indirectObject}
GIVE	give {bird|directObject} to {rod|indirectObject}
GIVE	give {bird|directObject} to {axe|indirectObject}
GIVE	give {bird|directObject} to {dwarf|indirectObject}
GIVE	give {cage|directObject} to {sliver|indirectObject}
GIVE	give {cage|directObject} to {bars|indirectObject}
GIVE	give {cage|directObject} to {silver bars|indirectObject}
GIVE	give {cage|directObject} to {all|indirectObject}
GIVE	give {cage|directObject} to {bird|indirectObject}
GIVE	give {cage|directObject} to {cage|indirectObject}
GIVE	give {cage|directObject} to {wicker cage|indirectObject}
GIVE	give {cage|directObject} to {gold nugget|indirectObject}
GIVE	give {cage|directObject} to {nugget|indirectObject}
GIVE	give {cage|directObject} to {keys|indirectObject}
GIVE	give {cage|directObject} to {food|indirectObject}
GIVE	give {cage|directObject} to {lamp|indirectObject}
GIVE	give {cage|directObject} to {grate|indirectObject}
GIVE	give {cage|directObject} to {dragon|indirectObject}
GIVE	give {cage|directObject} to {rug|indirectObject}
GIVE	give {cage|directObject} to {persian rug|indirectObject}
GIVE	give {cage|directObject} to {water|indirectObject}
GIVE	give {cage|directObject} to {plant|indirectObject}
GIVE	give {cage|directObject} to {emerald|indirectObject}
GIVE	give {cage|directObject} to {vase|indirectObject}
GIVE	give {cage|directObject} to {ming vase|indirectObject}
GIVE	give {cage|directObject} to {pillow|indirectObject}
GIVE	give {cage|directObject} to {pyramid|indirectObject}
GIVE	give {cage|directObject} to {beanstalk|indirectObject}
GIVE	give {cage|directObject} to {eggs|indirectObject}
GIVE	give {cage|directObject} to {door|indirectObject}
GIVE	give {cage|directObject} to {trident|indirectObject}
GIVE	give {cage|directObject} to {bear|indirectObject}
GIVE	give {cage|directObject} to {troll|indirectObject}
GIVE	give {cage|directObject} to {chain|indirectObject}
GIVE	give {cage|directObject} to {spices|indirectObject}
GIVE	give {cage|directObject} to {magazine|indirectObject}
GIVE	give {cage|directObject} to {pearl|indirectObject}
GIVE	give {cage|directObject} to {jewelry|indirectObject}
GIVE	give {cage|directObject} to {coins|indirectObject}
GIVE	give {cage|directObject} to {diamonds|indirectObject}
GIVE	give {cage|directObject} to {rod|indirectObject}
GIVE	give {cage|directObject} to {axe|indirectObject}
GIVE	give {cage|directObject} to {dwarf|indirectObject}
GIVE	give {wicker cage|directObject} to {sliver|indirectObject}
GIVE	give {wicker cage|directObject} to {bars|indirectObject}
GIVE	give {wicker cage|directObject} to {silver bars|indirectObject}
GIVE	give {wicker cage|directObject} to {all|indirectObject}
GIVE	give {wicker cage|directObject} to {bird|indirectObject}
GIVE	give {wicker cage|directObject} to {cage|indirectObject}
GIVE	give {wicker cage|directObject} to {wicker cage|indirectObject}
GIVE	give {wicker cage|directObject} to {gold nugget|indirectObject}
GIVE	give {wicker cage|directObject} to {nugget|indirectObject}
GIVE	give {wicker cage|directObject} to {keys|indirectObject}
GIVE	give {wicker cage|directObject} to {food|indirectObject}
GIVE	give {wicker cage|directObject} to {lamp|indirectObject}
GIVE	give {wicker cage|directObject} to {grate|indirectObject}
GIVE	give {wicker cage|directObject} to {dragon|indirectObject}
GIVE	give {wicker cage|directObject} to {rug|indirectObject}
GIVE	give {wicker cage|directObject} to {persian rug|indirectObject}
GIVE	give {wicker cage|directObject} to {water|indirectObject}
GIVE	give {wicker cage|directObject} to {plant|indirectObject}
GIVE	give {wicker cage|directObject} to {emerald|indirectObject}
GIVE	give {wicker cage|directObject} to {vase|indirectObject}
GIVE	give {wicker cage|directObject} to {ming vase|indirectObject}
GIVE	give {wicker cage|directObject} to {pillow|indirectObject}
GIVE	give {wicker cage|directObject} to {pyramid|indirectObject}
GIVE	give {wicker cage|directObject} to {beanstalk|indirectObject}
GIVE	give {wicker cage|directObject} to {eggs|indirectObject}
GIVE	give {wicker cage|directObject} to {door|indirectObject}
GIVE	give {wicker cage|directObject} to {trident|indirectObject}
GIVE	give {wicker cage|directObject} to {bear|indirectObject}
GIVE	give {wicker cage|directObject} to {troll|indirectObject}
GIVE	give {wicker cage|directObject} to {chain|indirectObject}
GIVE	give {wicker cage|directObject} to {spices|indirectObject}
GIVE	give {wicker cage|directObject} to {magazine|indirectObject}
GIVE	give {wicker cage|directObject} to {pearl|indirectObject}
GIVE	give {wicker cage|directObject} to {jewelry|indirectObject}
GIVE	give {wicker cage|directObject} to {coins|indirectObject}
GIVE	give {wicker cage|directObject} to {diamonds|indirectObject}
GIVE	give {wicker cage|directObject} to {rod|indirectObject}
GIVE	give {wicker cage|directObject} to {axe|indirectObject}
GIVE	give {wicker cage|directObject} to {dwarf|indirectObject}
GIVE	give {gold nugget|directObject} to {sliver|indirectObject}
GIVE	give {gold nugget|directObject} to {bars|indirectObject}
GIVE	give {gold nugget|directObject} to {silver bars|indirectObject}
GIVE	give {gold nugget|directObject} to {all|indirectObject}
GIVE	give {gold nugget|directObject} to {bird|indirectObject}
GIVE	give {gold nugget|directObject} to {cage|indirectObject}
GIVE	give {gold nugget|directObject} to {wicker cage|indirectObject}
GIVE	give {gold nugget|directObject} to {gold nugget|indirectObject}
GIVE	give {gold nugget|directObject} to {nugget|indirectObject}
GIVE	give {gold nugget|directObject} to {keys|indirectObject}
GIVE	give {gold nugget|directObject} to {food|indirectObject}
GIVE	give {gold nugget|directObject} to {lamp|indirectObject}
GIVE	give {gold nugget|directObject} to {grate|indirectObject}
GIVE	give {gold nugget|directObject} to {dragon|indirectObject}
GIVE	give {gold nugget|directObject} to {rug|indirectObject}
GIVE	give {gold nugget|directObject} to {persian rug|indirectObject}
GIVE	give {gold nugget|directObject} to {water|indirectObject}
GIVE	give {gold nugget|directObject} to {plant|indirectObject}
GIVE	give {gold nugget|directObject} to {emerald|indirectObject}
GIVE	give {gold nugget|directObject} to {vase|indirectObject}
GIVE	give {gold nugget|directObject} to {ming vase|indirectObject}
GIVE	give {gold nugget|directObject} to {pillow|indirectObject}
GIVE	give {gold nugget|directObject} to {pyramid|indirectObject}
GIVE	give {gold nugget|directObject} to {beanstalk|indirectObject}
GIVE	give {gold nugget|directObject} to {eggs|indirectObject}
GIVE	give {gold nugget|directObject} to {door|indirectObject}
GIVE	give {gold nugget|directObject} to {trident|indirectObject}
GIVE	give {gold nugget|directObject} to {bear|indirectObject}
GIVE	give {gold nugget|directObject} to {troll|indirectObject}
GIVE	give {gold nugget|directObject} to {chain|indirectObject}
GIVE	give {gold nugget|directObject} to {spices|indirectObject}
GIVE	give {gold nugget|directObject} to {magazine|indirectObject}
GIVE	give {gold nugget|directObject} to {pearl|indirectObject}
GIVE	give {gold nugget|directObject} to {jewelry|indirectObject}
GIVE	give {gold nugget|directObject} to {coins|indirectObject}
GIVE	give {gold nugget|directObject} to {diamonds|indirectObject}
GIVE	give {gold nugget|directObject} to {rod|indirectObject}
GIVE	give {gold nugget|directObject} to {axe|indirectObject}
GIVE	give {gold nugget|directObject} to {dwarf|indirectObject}
GIVE	give {nugget|directObject} to {sliver|indirectObject}
GIVE	give {nugget|directObject} to {bars|indirectObject}
GIVE	give {nugget|directObject} to {silver bars|indirectObject}
GIVE	give {nugget|directObject} to {all|indirectObject}
GIVE	give {nugget|directObject} to {bird|indirectObject}
GIVE	give {nugget|directObject} to {cage|indirectObject}
GIVE	give {nugget|directObject} to {wicker cage|indirectObject}
GIVE	give {nugget|directObject} to {gold nugget|indirectObject}
GIVE	give {nugget|directObject} to {nugget|indirectObject}
GIVE	give {nugget|directObject} to {keys|indirectObject}
GIVE	give {nugget|directObject} to {food|indirectObject}
GIVE	give {nugget|directObject} to {lamp|indirectObject}
GIVE	give {nugget|directObject} to {grate|indirectObject}
GIVE	give {nugget|directObject} to {dragon|indirectObject}
GIVE	give {nugget|directObject} to {rug|indirectObject}
GIVE	give {nugget|directObject} to {persian rug|indirectObject}
GIVE	give {nugget|directObject} to {water|indirectObject}
GIVE	give {nugget|directObject} to {plant|indirectObject}
GIVE	give {nugget|directObject} to {emerald|indirectObject}
GIVE	give {nugget|directObject} to {vase|indirectObject}
GIVE	give {nugget|directObject} to {ming vase|indirectObject}
GIVE	give {nugget|directObject} to {pillow|indirectObject}
GIVE	give {nugget|directObject} to {pyramid|indirectObject}
GIVE	give {nugget|directObject} to {beanstalk|indirectObject}
GIVE	give {nugget|directObject} to {eggs|indirectObject}
GIVE	give {nugget|directObject} to {door|indirectObject}
GIVE	give {nugget|directObject} to {trident|indirectObject}
GIVE	give {nugget|directObject} to {bear|indirectObject}
GIVE	give {nugget|directObject} to {troll|indirectObject}
GIVE	give {nugget|directObject} to {chain|indirectObject}
GIVE	give {nugget|directObject} to {spices|indirectObject}
GIVE	give {nugget|directObject} to {magazine|indirectObject}
GIVE	give {nugget|directObject} to {pearl|indirectObject}
GIVE	give {nugget|directObject} to {jewelry|indirectObject}
GIVE	give {nugget|directObject} to {coins|indirectObject}
GIVE	give {nugget|directObject} to {diamonds|indirectObject}
GIVE	give {nugget|directObject} to {rod|indirectObject}
GIVE	give {nugget|directObject} to {axe|indirectObject}
GIVE	give {nugget|directObject} to {dwarf|indirectObject}
GIVE	give {keys|directObject} to {sliver|indirectObject}
GIVE	give {keys|directObject} to {bars|indirectObject}
GIVE	give {keys|directObject} to {silver bars|indirectObject}
GIVE	give {keys|directObject} to {all|indirectObject}
GIVE	give {keys|directObject} to {bird|indirectObject}
GIVE	give {keys|directObject} to {cage|indirectObject}
GIVE	give {keys|directObject} to {wicker cage|indirectObject}
GIVE	give {keys|directObject} to {gold nugget|indirectObject}
GIVE	give {keys|directObject} to {nugget|indirectObject}
GIVE	give {keys|directObject} to {keys|indirectObject}
GIVE	give {keys|directObject} to {food|indirectObject}
GIVE	give {keys|directObject} to {lamp|indirectObject}
GIVE	give {keys|directObject} to {grate|indirectObject}
GIVE	give {keys|directObject} to {dragon|indirectObject}
GIVE	give {keys|directObject} to {rug|indirectObject}
GIVE	give {keys|directObject} to {persian rug|indirectObject}
GIVE	give {keys|directObject} to {water|indirectObject}
GIVE	give {keys|directObject} to {plant|indirectObject}
GIVE	give {keys|directObject} to {emerald|indirectObject}
GIVE	give {keys|directObject} to {vase|indirectObject}
GIVE	give {keys|directObject} to {ming vase|indirectObject}
GIVE	give {keys|directObject} to {pillow|indirectObject}
GIVE	give {keys|directObject} to {pyramid|indirectObject}
GIVE	give {keys|directObject} to {beanstalk|indirectObject}
GIVE	give {keys|directObject} to {eggs|indirectObject}
GIVE	give {keys|directObject} to {door|indirectObject}
GIVE	give {keys|directObject} to {trident|indirectObject}
GIVE	give {keys|directObject} to {bear|indirectObject}
GIVE	give {keys|directObject} to {troll|indirectObject}
GIVE	give {keys|directObject} to {chain|indirectObject}
GIVE	give {keys|directObject} to {spices|indirectObject}
GIVE	give {keys|directObject} to {magazine|indirectObject}
GIVE	give {keys|directObject} to {pearl|indirectObject}
GIVE	give {keys|directObject} to {jewelry|indirectObject}
GIVE	give {keys|directObject} to {coins|indirectObject}
GIVE	give {keys|directObject} to {diamonds|indirectObject}
GIVE	give {keys|directObject} to {rod|indirectObject}
GIVE	give {keys|directObject} to {axe|indirectObject}
GIVE	give {keys|directObject} to {dwarf|indirectObject}
GIVE	give {food|directObject} to {sliver|indirectObject}
GIVE	give {food|directObject} to {bars|indirectObject}
GIVE	give {food|directObject} to {silver bars|indirectObject}
GIVE	give {food|directObject} to {all|indirectObject}
GIVE	give {food|directObject} to {bird|indirectObject}
GIVE	give {food|directObject} to {cage|indirectObject}
GIVE	give {food|directObject} to {wicker cage|indirectObject}
GIVE	give {food|directObject} to {gold nugget|indirectObject}
GIVE	give {food|directObject} to {nugget|indirectObject}
GIVE	give {food|directObject} to {keys|indirectObject}
GIVE	give {food|directObject} to {food|indirectObject}
GIVE	give {food|directObject} to {lamp|indirectObject}
GIVE	give {food|directObject} to {grate|indirectObject}
GIVE	give {food|directObject} to {dragon|indirectObject}
GIVE	give {food|directObject} to {rug|indirectObject}
GIVE	give {food|directObject} to {persian rug|indirectObject}
GIVE	give {food|directObject} to {water|indirectObject}
GIVE	give {food|directObject} to {plant|indirectObject}
GIVE	give {food|directObject} to {emerald|indirectObject}
GIVE	give {food|directObject} to {vase|indirectObject}
GIVE	give {food|directObject} to {ming vase|indirectObject}
GIVE	give {food|directObject} to {pillow|indirectObject}
GIVE	give {food|directObject} to {pyramid|indirectObject}
GIVE	give {food|directObject} to {beanstalk|indirectObject}
GIVE	give {food|directObject} to {eggs|indirectObject}
GIVE	give {food|directObject} to {door|indirectObject}
GIVE	give {food|directObject} to {trident|indirectObject}
GIVE	give {food|directObject} to {bear|indirectObject}
GIVE	give {food|directObject} to {troll|indirectObject}
GIVE	give {food|directObject} to {chain|indirectObject}
GIVE	give {food|directObject} to {spices|indirectObject}
GIVE	give {food|directObject} to {magazine|indirectObject}
GIVE	give {food|directObject} to {pearl|indirectObject}
GIVE	give {food|directObject} to {jewelry|indirectObject}
GIVE	give {food|directObject} to {coins|indirectObject}
GIVE	give {food|directObject} to {diamonds|indirectObject}
GIVE	give {food|directObject} to {rod|indirectObject}
GIVE	give {food|directObject} to {axe|indirectObject}
GIVE	give {food|directObject} to {dwarf|indirectObject}
GIVE	give {lamp|directObject} to {sliver|indirectObject}
GIVE	give {lamp|directObject} to {bars|indirectObject}
GIVE	give {lamp|directObject} to {silver bars|indirectObject}
GIVE	give {lamp|directObject} to {all|indirectObject}
GIVE	give {lamp|directObject} to {bird|indirectObject}
GIVE	give {lamp|directObject} to {cage|indirectObject}
GIVE	give {lamp|directObject} to {wicker cage|indirectObject}
GIVE	give {lamp|directObject} to {gold nugget|indirectObject}
GIVE	give {lamp|directObject} to {nugget|indirectObject}
GIVE	give {lamp|directObject} to {keys|indirectObject}
GIVE	give {lamp|directObject} to {food|indirectObject}
GIVE	give {lamp|directObject} to {lamp|indirectObject}
GIVE	give {lamp|directObject} to {grate|indirectObject}
GIVE	give {lamp|directObject} to {dragon|indirectObject}
GIVE	give {lamp|directObject} to {rug|indirectObject}
GIVE	give {lamp|directObject} to {persian rug|indirectObject}
GIVE	give {lamp|directObject} to {water|indirectObject}
GIVE	give {lamp|directObject} to {plant|indirectObject}
GIVE	give {lamp|directObject} to {emerald|indirectObject}
GIVE	give {lamp|directObject} to {vase|indirectObject}
GIVE	give {lamp|directObject} to {ming vase|indirectObject}
GIVE	give {lamp|directObject} to {pillow|indirectObject}
GIVE	give {lamp|directObject} to {pyramid|indirectObject}
GIVE	give {lamp|directObject} to {beanstalk|indirectObject}
GIVE	give {lamp|directObject} to {eggs|indirectObject}
GIVE	give {lamp|directObject} to {door|indirectObject}
GIVE	give {lamp|directObject} to {trident|indirectObject}
GIVE	give {lamp|directObject} to {bear|indirectObject}
GIVE	give {lamp|directObject} to {troll|indirectObject}
GIVE	give {lamp|directObject} to {chain|indirectObject}
GIVE	give {lamp|directObject} to {spices|indirectObject}
GIVE	give {lamp|directObject} to {magazine|indirectObject}
GIVE	give {lamp|directObject} to {pearl|indirectObject}
GIVE	give {lamp|directObject} to {jewelry|indirectObject}
GIVE	give {lamp|directObject} to {coins|indirectObject}
GIVE	give {lamp|directObject} to {diamonds|indirectObject}
GIVE	give {lamp|directObject} to {rod|indirectObject}
GIVE	give {lamp|directObject} to {axe|indirectObject}
GIVE	give {lamp|directObject} to {dwarf|indirectObject}
GIVE	give {grate|directObject} to {sliver|indirectObject}
GIVE	give {grate|directObject} to {bars|indirectObject}
GIVE	give {grate|directObject} to {silver bars|indirectObject}
GIVE	give {grate|directObject} to {all|indirectObject}
GIVE	give {grate|directObject} to {bird|indirectObject}
GIVE	give {grate|directObject} to {cage|indirectObject}
GIVE	give {grate|directObject} to {wicker cage|indirectObject}
GIVE	give {grate|directObject} to {gold nugget|indirectObject}
GIVE	give {grate|directObject} to {nugget|indirectObject}
GIVE	give {grate|directObject} to {keys|indirectObject}
GIVE	give {grate|directObject} to {food|indirectObject}
GIVE	give {grate|directObject} to {lamp|indirectObject}
GIVE	give {grate|directObject} to {grate|indirectObject}
GIVE	give {grate|directObject} to {dragon|indirectObject}
GIVE	give {grate|directObject} to {rug|indirectObject}
GIVE	give {grate|directObject} to {persian rug|indirectObject}
GIVE	give {grate|directObject} to {water|indirectObject}
GIVE	give {grate|directObject} to {plant|indirectObject}
GIVE	give {grate|directObject} to {emerald|indirectObject}
GIVE	give {grate|directObject} to {vase|indirectObject}
GIVE	give {grate|directObject} to {ming vase|indirectObject}
GIVE	give {grate|directObject} to {pillow|indirectObject}
GIVE	give {grate|directObject} to {pyramid|indirectObject}
GIVE	give {grate|directObject} to {beanstalk|indirectObject}
GIVE	give {grate|directObject} to {eggs|indirectObject}
GIVE	give {grate|directObject} to {door|indirectObject}
GIVE	give {grate|directObject} to {trident|indirectObject}
GIVE	give {grate|directObject} to {bear|indirectObject}
GIVE	give {grate|directObject} to {troll|indirectObject}
GIVE	give {grate|directObject} to {chain|indirectObject}
GIVE	give {grate|directObject} to {spices|indirectObject}
GIVE	give {grate|directObject} to {magazine|indirectObject}
GIVE	give {grate|directObject} to {pearl|indirectObject}
GIVE	give {grate|directObject} to {jewelry|indirectObject}
GIVE	give {grate|directObject} to {coins|indirectObject}
GIVE	give {grate|directObject} to {diamonds|indirectObject}
GIVE	give {grate|directObject} to {rod|indirectObject}
GIVE	give {grate|directObject} to {axe|indirectObject}
GIVE	give {grate|directObject} to {dwarf|indirectObject}
GIVE	give {dragon|directObject} to {sliver|indirectObject}
GIVE	give {dragon|directObject} to {bars|indirectObject}
GIVE	give {dragon|directObject} to {silver bars|indirectObject}
GIVE	give {dragon|directObject} to {all|indirectObject}
GIVE	give {dragon|directObject} to {bird|indirectObject}
GIVE	give {dragon|directObject} to {cage|indirectObject}
GIVE	give {dragon|directObject} to {wicker cage|indirectObject}
GIVE	give {dragon|directObject} to {gold nugget|indirectObject}
GIVE	give {dragon|directObject} to {nugget|indirectObject}
GIVE	give {dragon|directObject} to {keys|indirectObject}
GIVE	give {dragon|directObject} to {food|indirectObject}
GIVE	give {dragon|directObject} to {lamp|indirectObject}
GIVE	give {dragon|directObject} to {grate|indirectObject}
GIVE	give {dragon|directObject} to {dragon|indirectObject}
GIVE	give {dragon|directObject} to {rug|indirectObject}
GIVE	give {dragon|directObject} to {persian rug|indirectObject}
GIVE	give {dragon|directObject} to {water|indirectObject}
GIVE	give {dragon|directObject} to {plant|indirectObject}
GIVE	give {dragon|directObject} to {emerald|indirectObject}
GIVE	give {dragon|directObject} to {vase|indirectObject}
GIVE	give {dragon|directObject} to {ming vase|indirectObject}
GIVE	give {dragon|directObject} to {pillow|indirectObject}
GIVE	give {dragon|directObject} to {pyramid|indirectObject}
GIVE	give {dragon|directObject} to {beanstalk|indirectObject}
GIVE	give {dragon|directObject} to {eggs|indirectObject}
GIVE	give {dragon|directObject} to {door|indirectObject}
GIVE	give {dragon|directObject} to {trident|indirectObject}
GIVE	give {dragon|directObject} to {bear|indirectObject}
GIVE	give {dragon|directObject} to {troll|indirectObject}
GIVE	give {dragon|directObject} to {chain|indirectObject}
GIVE	give {dragon|directObject} to {spices|indirectObject}
GIVE	give {dragon|directObject} to {magazine|indirectObject}
GIVE	give {dragon|directObject} to {pearl|indirectObject}
GIVE	give {dragon|directObject} to {jewelry|indirectObject}
GIVE	give {dragon|directObject} to {coins|indirectObject}
GIVE	give {dragon|directObject} to {diamonds|indirectObject}
GIVE	give {dragon|directObject} to {rod|indirectObject}
GIVE	give {dragon|directObject} to {axe|indirectObject}
GIVE	give {dragon|directObject} to {dwarf|indirectObject}
GIVE	give {rug|directObject} to {sliver|indirectObject}
GIVE	give {rug|directObject} to {bars|indirectObject}
GIVE	give {rug|directObject} to {silver bars|indirectObject}
GIVE	give {rug|directObject} to {all|indirectObject}
GIVE	give {rug|directObject} to {bird|indirectObject}
GIVE	give {rug|directObject} to {cage|indirectObject}
GIVE	give {rug|directObject} to {wicker cage|indirectObject}
GIVE	give {rug|directObject} to {gold nugget|indirectObject}
GIVE	give {rug|directObject} to {nugget|indirectObject}
GIVE	give {rug|directObject} to {keys|indirectObject}
GIVE	give {rug|directObject} to {food|indirectObject}
GIVE	give {rug|directObject} to {lamp|indirectObject}
GIVE	give {rug|directObject} to {grate|indirectObject}
GIVE	give {rug|directObject} to {dragon|indirectObject}
GIVE	give {rug|directObject} to {rug|indirectObject}
GIVE	give {rug|directObject} to {persian rug|indirectObject}
GIVE	give {rug|directObject} to {water|indirectObject}
GIVE	give {rug|directObject} to {plant|indirectObject}
GIVE	give {rug|directObject} to {emerald|indirectObject}
GIVE	give {rug|directObject} to {vase|indirectObject}
GIVE	give {rug|directObject} to {ming vase|indirectObject}
GIVE	give {rug|directObject} to {pillow|indirectObject}
GIVE	give {rug|directObject} to {pyramid|indirectObject}
GIVE	give {rug|directObject} to {beanstalk|indirectObject}
GIVE	give {rug|directObject} to {eggs|indirectObject}
GIVE	give {rug|directObject} to {door|indirectObject}
GIVE	give {rug|directObject} to {trident|indirectObject}
GIVE	give {rug|directObject} to {bear|indirectObject}
GIVE	give {rug|directObject} to {troll|indirectObject}
GIVE	give {rug|directObject} to {chain|indirectObject}
GIVE	give {rug|directObject} to {spices|indirectObject}
GIVE	give {rug|directObject} to {magazine|indirectObject}
GIVE	give {rug|directObject} to {pearl|indirectObject}
GIVE	give {rug|directObject} to {jewelry|indirectObject}
GIVE	give {rug|directObject} to {coins|indirectObject}
GIVE	give {rug|directObject} to {diamonds|indirectObject}
GIVE	give {rug|directObject} to {rod|indirectObject}
GIVE	give {rug|directObject} to {axe|indirectObject}
GIVE	give {rug|directObject} to {dwarf|indirectObject}
GIVE	give {persian rug|directObject} to {sliver|indirectObject}
GIVE	give {persian rug|directObject} to {bars|indirectObject}
GIVE	give {persian rug|directObject} to {silver bars|indirectObject}
GIVE	give {persian rug|directObject} to {all|indirectObject}
GIVE	give {persian rug|directObject} to {bird|indirectObject}
GIVE	give {persian rug|directObject} to {cage|indirectObject}
GIVE	give {persian rug|directObject} to {wicker cage|indirectObject}
GIVE	give {persian rug|directObject} to {gold nugget|indirectObject}
GIVE	give {persian rug|directObject} to {nugget|indirectObject}
GIVE	give {persian rug|directObject} to {keys|indirectObject}
GIVE	give {persian rug|directObject} to {food|indirectObject}
GIVE	give {persian rug|directObject} to {lamp|indirectObject}
GIVE	give {persian rug|directObject} to {grate|indirectObject}
GIVE	give {persian rug|directObject} to {dragon|indirectObject}
GIVE	give {persian rug|directObject} to {rug|indirectObject}
GIVE	give {persian rug|directObject} to {persian rug|indirectObject}
GIVE	give {persian rug|directObject} to {water|indirectObject}
GIVE	give {persian rug|directObject} to {plant|indirectObject}
GIVE	give {persian rug|directObject} to {emerald|indirectObject}
GIVE	give {persian rug|directObject} to {vase|indirectObject}
GIVE	give {persian rug|directObject} to {ming vase|indirectObject}
GIVE	give {persian rug|directObject} to {pillow|indirectObject}
GIVE	give {persian rug|directObject} to {pyramid|indirectObject}
GIVE	give {persian rug|directObject} to {beanstalk|indirectObject}
GIVE	give {persian rug|directObject} to {eggs|indirectObject}
GIVE	give {persian rug|directObject} to {door|indirectObject}
GIVE	give {persian rug|directObject} to {trident|indirectObject}
GIVE	give {persian rug|directObject} to {bear|indirectObject}
GIVE	give {persian rug|directObject} to {troll|indirectObject}
GIVE	give {persian rug|directObject} to {chain|indirectObject}
GIVE	give {persian rug|directObject} to {spices|indirectObject}
GIVE	give {persian rug|directObject} to {magazine|indirectObject}
GIVE	give {persian rug|directObject} to {pearl|indirectObject}
GIVE	give {persian rug|directObject} to {jewelry|indirectObject}
GIVE	give {persian rug|directObject} to {coins|indirectObject}
GIVE	give {persian rug|directObject} to {diamonds|indirectObject}
GIVE	give {persian rug|directObject} to {rod|indirectObject}
GIVE	give {persian rug|directObject} to {axe|indirectObject}
GIVE	give {persian rug|directObject} to {dwarf|indirectObject}
GIVE	give {water|directObject} to {sliver|indirectObject}
GIVE	give {water|directObject} to {bars|indirectObject}
GIVE	give {water|directObject} to {silver bars|indirectObject}
GIVE	give {water|directObject} to {all|indirectObject}
GIVE	give {water|directObject} to {bird|indirectObject}
GIVE	give {water|directObject} to {cage|indirectObject}
GIVE	give {water|directObject} to {wicker cage|indirectObject}
GIVE	give {water|directObject} to {gold nugget|indirectObject}
GIVE	give {water|directObject} to {nugget|indirectObject}
GIVE	give {water|directObject} to {keys|indirectObject}
GIVE	give {water|directObject} to {food|indirectObject}
GIVE	give {water|directObject} to {lamp|indirectObject}
GIVE	give {water|directObject} to {grate|indirectObject}
GIVE	give {water|directObject} to {dragon|indirectObject}
GIVE	give {water|directObject} to {rug|indirectObject}
GIVE	give {water|directObject} to {persian rug|indirectObject}
GIVE	give {water|directObject} to {water|indirectObject}
GIVE	give {water|directObject} to {plant|indirectObject}
GIVE	give {water|directObject} to {emerald|indirectObject}
GIVE	give {water|directObject} to {vase|indirectObject}
GIVE	give {water|directObject} to {ming vase|indirectObject}
GIVE	give {water|directObject} to {pillow|indirectObject}
GIVE	give {water|directObject} to {pyramid|indirectObject}
GIVE	give {water|directObject} to {beanstalk|indirectObject}
GIVE	give {water|directObject} to {eggs|indirectObject}
GIVE	give {water|directObject} to {door|indirectObject}
GIVE	give {water|directObject} to {trident|indirectObject}
GIVE	give {water|directObject} to {bear|indirectObject}
GIVE	give {water|directObject} to {troll|indirectObject}
GIVE	give {water|directObject} to {chain|indirectObject}
GIVE	give {water|directObject} to {spices|indirectObject}
GIVE	give {water|directObject} to {magazine|indirectObject}
GIVE	give {water|directObject} to {pearl|indirectObject}
GIVE	give {water|directObject} to {jewelry|indirectObject}
GIVE	give {water|directObject} to {coins|indirectObject}
GIVE	give {water|directObject} to {diamonds|indirectObject}
GIVE	give {water|directObject} to {rod|indirectObject}
GIVE	give {water|directObject} to {axe|indirectObject}
GIVE	give {water|directObject} to {dwarf|indirectObject}
GIVE	give {plant|directObject} to {sliver|indirectObject}
GIVE	give {plant|directObject} to {bars|indirectObject}
GIVE	give {plant|directObject} to {silver bars|indirectObject}
GIVE	give {plant|directObject} to {all|indirectObject}
GIVE	give {plant|directObject} to {bird|indirectObject}
GIVE	give {plant|directObject} to {cage|indirectObject}
GIVE	give {plant|directObject} to {wicker cage|indirectObject}
GIVE	give {plant|directObject} to {gold nugget|indirectObject}
GIVE	give {plant|directObject} to {nugget|indirectObject}
GIVE	give {plant|directObject} to {keys|indirectObject}
GIVE	give {plant|directObject} to {food|indirectObject}
GIVE	give {plant|directObject} to {lamp|indirectObject}
GIVE	give {plant|directObject} to {grate|indirectObject}
GIVE	give {plant|directObject} to {dragon|indirectObject}
GIVE	give {plant|directObject} to {rug|indirectObject}
GIVE	give {plant|directObject} to {persian rug|indirectObject}
GIVE	give {plant|directObject} to {water|indirectObject}
GIVE	give {plant|directObject} to {plant|indirectObject}
GIVE	give {plant|directObject} to {emerald|indirectObject}
GIVE	give {plant|directObject} to {vase|indirectObject}
GIVE	give {plant|directObject} to {ming vase|indirectObject}
GIVE	give {plant|directObject} to {pillow|indirectObject}
GIVE	give {plant|directObject} to {pyramid|indirectObject}
GIVE	give {plant|directObject} to {beanstalk|indirectObject}
GIVE	give {plant|directObject} to {eggs|indirectObject}
GIVE	give {plant|directObject} to {door|indirectObject}
GIVE	give {plant|directObject} to {trident|indirectObject}
GIVE	give {plant|directObject} to {bear|indirectObject}
GIVE	give {plant|directObject} to {troll|indirectObject}
GIVE	give {plant|directObject} to {chain|indirectObject}
GIVE	give {plant|directObject} to {spices|indirectObject}
GIVE	give {plant|directObject} to {magazine|indirectObject}
GIVE	give {plant|directObject} to {pearl|indirectObject}
GIVE	give {plant|directObject} to {jewelry|indirectObject}
GIVE	give {plant|directObject} to {coins|indirectObject}
GIVE	give {plant|directObject} to {diamonds|indirectObject}
GIVE	give {plant|directObject} to {rod|indirectObject}
GIVE	give {plant|directObject} to {axe|indirectObject}
GIVE	give {plant|directObject} to {dwarf|indirectObject}
GIVE	give {emerald|directObject} to {sliver|indirectObject}
GIVE	give {emerald|directObject} to {bars|indirectObject}
GIVE	give {emerald|directObject} to {silver bars|indirectObject}
GIVE	give {emerald|directObject} to {all|indirectObject}
GIVE	give {emerald|directObject} to {bird|indirectObject}
GIVE	give {emerald|directObject} to {cage|indirectObject}
GIVE	give {emerald|directObject} to {wicker cage|indirectObject}
GIVE	give {emerald|directObject} to {gold nugget|indirectObject}
GIVE	give {emerald|directObject} to {nugget|indirectObject}
GIVE	give {emerald|directObject} to {keys|indirectObject}
GIVE	give {emerald|directObject} to {food|indirectObject}
GIVE	give {emerald|directObject} to {lamp|indirectObject}
GIVE	give {emerald|directObject} to {grate|indirectObject}
GIVE	give {emerald|directObject} to {dragon|indirectObject}
GIVE	give {emerald|directObject} to {rug|indirectObject}
GIVE	give {emerald|directObject} to {persian rug|indirectObject}
GIVE	give {emerald|directObject} to {water|indirectObject}
GIVE	give {emerald|directObject} to {plant|indirectObject}
GIVE	give {emerald|directObject} to {emerald|indirectObject}
GIVE	give {emerald|directObject} to {vase|indirectObject}
GIVE	give {emerald|directObject} to {ming vase|indirectObject}
GIVE	give {emerald|directObject} to {pillow|indirectObject}
GIVE	give {emerald|directObject} to {pyramid|indirectObject}
GIVE	give {emerald|directObject} to {beanstalk|indirectObject}
GIVE	give {emerald|directObject} to {eggs|indirectObject}
GIVE	give {emerald|directObject} to {door|indirectObject}
GIVE	give {emerald|directObject} to {trident|indirectObject}
GIVE	give {emerald|directObject} to {bear|indirectObject}
GIVE	give {emerald|directObject} to {troll|indirectObject}
GIVE	give {emerald|directObject} to {chain|indirectObject}
GIVE	give {emerald|directObject} to {spices|indirectObject}
GIVE	give {emerald|directObject} to {magazine|indirectObject}
GIVE	give {emerald|directObject} to {pearl|indirectObject}
GIVE	give {emerald|directObject} to {jewelry|indirectObject}
GIVE	give {emerald|directObject} to {coins|indirectObject}
GIVE	give {emerald|directObject} to {diamonds|indirectObject}
GIVE	give {emerald|directObject} to {rod|indirectObject}
GIVE	give {emerald|directObject} to {axe|indirectObject}
GIVE	give {emerald|directObject} to {dwarf|indirectObject}
GIVE	give {vase|directObject} to {sliver|indirectObject}
GIVE	give {vase|directObject} to {bars|indirectObject}
GIVE	give {vase|directObject} to {silver bars|indirectObject}
GIVE	give {vase|directObject} to {all|indirectObject}
GIVE	give {vase|directObject} to {bird|indirectObject}
GIVE	give {vase|directObject} to {cage|indirectObject}
GIVE	give {vase|directObject} to {wicker cage|indirectObject}
GIVE	give {vase|directObject} to {gold nugget|indirectObject}
GIVE	give {vase|directObject} to {nugget|indirectObject}
GIVE	give {vase|directObject} to {keys|indirectObject}
GIVE	give {vase|directObject} to {food|indirectObject}
GIVE	give {vase|directObject} to {lamp|indirectObject}
GIVE	give {vase|directObject} to {grate|indirectObject}
GIVE	give {vase|directObject} to {dragon|indirectObject}
GIVE	give {vase|directObject} to {rug|indirectObject}
GIVE	give {vase|directObject} to {persian rug|indirectObject}
GIVE	give {vase|directObject} to {water|indirectObject}
GIVE	give {vase|directObject} to {plant|indirectObject}
GIVE	give {vase|directObject} to {emerald|indirectObject}
GIVE	give {vase|directObject} to {vase|indirectObject}
GIVE	give {vase|directObject} to {ming vase|indirectObject}
GIVE	give {vase|directObject} to {pillow|indirectObject}
GIVE	give {vase|directObject} to {pyramid|indirectObject}
GIVE	give {vase|directObject} to {beanstalk|indirectObject}
GIVE	give {vase|directObject} to {eggs|indirectObject}
GIVE	give {vase|directObject} to {door|indirectObject}
GIVE	give {vase|directObject} to {trident|indirectObject}
GIVE	give {vase|directObject} to {bear|indirectObject}
GIVE	give {vase|directObject} to {troll|indirectObject}
GIVE	give {vase|directObject} to {chain|indirectObject}
GIVE	give {vase|directObject} to {spices|indirectObject}
GIVE	give {vase|directObject} to {magazine|indirectObject}
GIVE	give {vase|directObject} to {pearl|indirectObject}
GIVE	give {vase|directObject} to {jewelry|indirectObject}
GIVE	give {vase|directObject} to {coins|indirectObject}
GIVE	give {vase|directObject} to {diamonds|indirectObject}
GIVE	give {vase|directObject} to {rod|indirectObject}
GIVE	give {vase|directObject} to {axe|indirectObject}
GIVE	give {vase|directObject} to {dwarf|indirectObject}
GIVE	give {ming vase|directObject} to {sliver|indirectObject}
GIVE	give {ming vase|directObject} to {bars|indirectObject}
GIVE	give {ming vase|directObject} to {silver bars|indirectObject}
GIVE	give {ming vase|directObject} to {all|indirectObject}
GIVE	give {ming vase|directObject} to {bird|indirectObject}
GIVE	give {ming vase|directObject} to {cage|indirectObject}
GIVE	give {ming vase|directObject} to {wicker cage|indirectObject}
GIVE	give {ming vase|directObject} to {gold nugget|indirectObject}
GIVE	give {ming vase|directObject} to {nugget|indirectObject}
GIVE	give {ming vase|directObject} to {keys|indirectObject}
GIVE	give {ming vase|directObject} to {food|indirectObject}
GIVE	give {ming vase|directObject} to {lamp|indirectObject}
GIVE	give {ming vase|directObject} to {grate|indirectObject}
GIVE	give {ming vase|directObject} to {dragon|indirectObject}
GIVE	give {ming vase|directObject} to {rug|indirectObject}
GIVE	give {ming vase|directObject} to {persian rug|indirectObject}
GIVE	give {ming vase|directObject} to {water|indirectObject}
GIVE	give {ming vase|directObject} to {plant|indirectObject}
GIVE	give {ming vase|directObject} to {emerald|indirectObject}
GIVE	give {ming vase|directObject} to {vase|indirectObject}
GIVE	give {ming vase|directObject} to {ming vase|indirectObject}
GIVE	give {ming vase|directObject} to {pillow|indirectObject}
GIVE	give {ming vase|directObject} to {pyramid|indirectObject}
GIVE	give {ming vase|directObject} to {beanstalk|indirectObject}
GIVE	give {ming vase|directObject} to {eggs|indirectObject}
GIVE	give {ming vase|directObject} to {door|indirectObject}
GIVE	give {ming vase|directObject} to {trident|indirectObject}
GIVE	give {ming vase|directObject} to {bear|indirectObject}
GIVE	give {ming vase|directObject} to {troll|indirectObject}
GIVE	give {ming vase|directObject} to {chain|indirectObject}
GIVE	give {ming vase|directObject} to {spices|indirectObject}
GIVE	give {ming vase|directObject} to {magazine|indirectObject}
GIVE	give {ming vase|directObject} to {pearl|indirectObject}
GIVE	give {ming vase|directObject} to {jewelry|indirectObject}
GIVE	give {ming vase|directObject} to {coins|indirectObject}
GIVE	give {ming vase|directObject} to {diamonds|indirectObject}
GIVE	give {ming vase|directObject} to {rod|indirectObject}
GIVE	give {ming vase|directObject} to {axe|indirectObject}
GIVE	give {ming vase|directObject} to {dwarf|indirectObject}
GIVE	give {pillow|directObject} to {sliver|indirectObject}
GIVE	give {pillow|directObject} to {bars|indirectObject}
GIVE	give {pillow|directObject} to {silver bars|indirectObject}
GIVE	give {pillow|directObject} to {all|indirectObject}
GIVE	give {pillow|directObject} to {bird|indirectObject}
GIVE	give {pillow|directObject} to {cage|indirectObject}
GIVE	give {pillow|directObject} to {wicker cage|indirectObject}
GIVE	give {pillow|directObject} to {gold nugget|indirectObject}
GIVE	give {pillow|directObject} to {nugget|indirectObject}
GIVE	give {pillow|directObject} to {keys|indirectObject}
GIVE	give {pillow|directObject} to {food|indirectObject}
GIVE	give {pillow|directObject} to {lamp|indirectObject}
GIVE	give {pillow|directObject} to {grate|indirectObject}
GIVE	give {pillow|directObject} to {dragon|indirectObject}
GIVE	give {pillow|directObject} to {rug|indirectObject}
GIVE	give {pillow|directObject} to {persian rug|indirectObject}
GIVE	give {pillow|directObject} to {water|indirectObject}
GIVE	give {pillow|directObject} to {plant|indirectObject}
GIVE	give {pillow|directObject} to {emerald|indirectObject}
GIVE	give {pillow|directObject} to {vase|indirectObject}
GIVE	give {pillow|directObject} to {ming vase|indirectObject}
GIVE	give {pillow|directObject} to {pillow|indirectObject}
GIVE	give {pillow|directObject} to {pyramid|indirectObject}
GIVE	give {pillow|directObject} to {beanstalk|indirectObject}
GIVE	give {pillow|directObject} to {eggs|indirectObject}
GIVE	give {pillow|directObject} to {door|indirectObject}
GIVE	give {pillow|directObject} to {trident|indirectObject}
GIVE	give {pillow|directObject} to {bear|indirectObject}
GIVE	give {pillow|directObject} to {troll|indirectObject}
GIVE	give {pillow|directObject} to {chain|indirectObject}
GIVE	give {pillow|directObject} to {spices|indirectObject}
GIVE	give {pillow|directObject} to {magazine|indirectObject}
GIVE	give {pillow|directObject} to {pearl|indirectObject}
GIVE	give {pillow|directObject} to {jewelry|indirectObject}
GIVE	give {pillow|directObject} to {coins|indirectObject}
GIVE	give {pillow|directObject} to {diamonds|indirectObject}
GIVE	give {pillow|directObject} to {rod|indirectObject}
GIVE	give {pillow|directObject} to {axe|indirectObject}
GIVE	give {pillow|directObject} to {dwarf|indirectObject}
GIVE	give {pyramid|directObject} to {sliver|indirectObject}
GIVE	give {pyramid|directObject} to {bars|indirectObject}
GIVE	give {pyramid|directObject} to {silver bars|indirectObject}
GIVE	give {pyramid|directObject} to {all|indirectObject}
GIVE	give {pyramid|directObject} to {bird|indirectObject}
GIVE	give {pyramid|directObject} to {cage|indirectObject}
GIVE	give {pyramid|directObject} to {wicker cage|indirectObject}
GIVE	give {pyramid|directObject} to {gold nugget|indirectObject}
GIVE	give {pyramid|directObject} to {nugget|indirectObject}
GIVE	give {pyramid|directObject} to {keys|indirectObject}
GIVE	give {pyramid|directObject} to {food|indirectObject}
GIVE	give {pyramid|directObject} to {lamp|indirectObject}
GIVE	give {pyramid|directObject} to {grate|indirectObject}
GIVE	give {pyramid|directObject} to {dragon|indirectObject}
GIVE	give {pyramid|directObject} to {rug|indirectObject}
GIVE	give {pyramid|directObject} to {persian rug|indirectObject}
GIVE	give {pyramid|directObject} to {water|indirectObject}
GIVE	give {pyramid|directObject} to {plant|indirectObject}
GIVE	give {pyramid|directObject} to {emerald|indirectObject}
GIVE	give {pyramid|directObject} to {vase|indirectObject}
GIVE	give {pyramid|directObject} to {ming vase|indirectObject}
GIVE	give {pyramid|directObject} to {pillow|indirectObject}
GIVE	give {pyramid|directObject} to {pyramid|indirectObject}
GIVE	give {pyramid|directObject} to {beanstalk|indirectObject}
GIVE	give {pyramid|directObject} to {eggs|indirectObject}
GIVE	give {pyramid|directObject} to {door|indirectObject}
GIVE	give {pyramid|directObject} to {trident|indirectObject}
GIVE	give {pyramid|directObject} to {bear|indirectObject}
GIVE	give {pyramid|directObject} to {troll|indirectObject}
GIVE	give {pyramid|directObject} to {chain|indirectObject}
GIVE	give {pyramid|directObject} to {spices|indirectObject}
GIVE	give {pyramid|directObject} to {magazine|indirectObject}
GIVE	give {pyramid|directObject} to {pearl|indirectObject}
GIVE	give {pyramid|directObject} to {jewelry|indirectObject}
GIVE	give {pyramid|directObject} to {coins|indirectObject}
GIVE	give {pyramid|directObject} to {diamonds|indirectObject}
GIVE	give {pyramid|directObject} to {rod|indirectObject}
GIVE	give {pyramid|directObject} to {axe|indirectObject}
GIVE	give {pyramid|directObject} to {dwarf|indirectObject}
GIVE	give {beanstalk|directObject} to {sliver|indirectObject}
GIVE	give {beanstalk|directObject} to {bars|indirectObject}
GIVE	give {beanstalk|directObject} to {silver bars|indirectObject}
GIVE	give {beanstalk|directObject} to {all|indirectObject}
GIVE	give {beanstalk|directObject} to {bird|indirectObject}
GIVE	give {beanstalk|directObject} to {cage|indirectObject}
GIVE	give {beanstalk|directObject} to {wicker cage|indirectObject}
GIVE	give {beanstalk|directObject} to {gold nugget|indirectObject}
GIVE	give {beanstalk|directObject} to {nugget|indirectObject}
GIVE	give {beanstalk|directObject} to {keys|indirectObject}
GIVE	give {beanstalk|directObject} to {food|indirectObject}
GIVE	give {beanstalk|directObject} to {lamp|indirectObject}
GIVE	give {beanstalk|directObject} to {grate|indirectObject}
GIVE	give {beanstalk|directObject} to {dragon|indirectObject}
GIVE	give {beanstalk|directObject} to {rug|indirectObject}
GIVE	give {beanstalk|directObject} to {persian rug|indirectObject}
GIVE	give {beanstalk|directObject} to {water|indirectObject}
GIVE	give {beanstalk|directObject} to {plant|indirectObject}
GIVE	give {beanstalk|directObject} to {emerald|indirectObject}
GIVE	give {beanstalk|directObject} to {vase|indirectObject}
GIVE	give {beanstalk|directObject} to {ming vase|indirectObject}
GIVE	give {beanstalk|directObject} to {pillow|indirectObject}
GIVE	give {beanstalk|directObject} to {pyramid|indirectObject}
GIVE	give {beanstalk|directObject} to {beanstalk|indirectObject}
GIVE	give {beanstalk|directObject} to {eggs|indirectObject}
GIVE	give {beanstalk|directObject} to {door|indirectObject}
GIVE	give {beanstalk|directObject} to {trident|indirectObject}
GIVE	give {beanstalk|directObject} to {bear|indirectObject}
GIVE	give {beanstalk|directObject} to {troll|indirectObject}
GIVE	give {beanstalk|directObject} to {chain|indirectObject}
GIVE	give {beanstalk|directObject} to {spices|indirectObject}
GIVE	give {beanstalk|directObject} to {magazine|indirectObject}
GIVE	give {beanstalk|directObject} to {pearl|indirectObject}
GIVE	give {beanstalk|directObject} to {jewelry|indirectObject}
GIVE	give {beanstalk|directObject} to {coins|indirectObject}
GIVE	give {beanstalk|directObject} to {diamonds|indirectObject}
GIVE	give {beanstalk|directObject} to {rod|indirectObject}
GIVE	give {beanstalk|directObject} to {axe|indirectObject}
GIVE	give {beanstalk|directObject} to {dwarf|indirectObject}
GIVE	give {eggs|directObject} to {sliver|indirectObject}
GIVE	give {eggs|directObject} to {bars|indirectObject}
GIVE	give {eggs|directObject} to {silver bars|indirectObject}
GIVE	give {eggs|directObject} to {all|indirectObject}
GIVE	give {eggs|directObject} to {bird|indirectObject}
GIVE	give {eggs|directObject} to {cage|indirectObject}
GIVE	give {eggs|directObject} to {wicker cage|indirectObject}
GIVE	give {eggs|directObject} to {gold nugget|indirectObject}
GIVE	give {eggs|directObject} to {nugget|indirectObject}
GIVE	give {eggs|directObject} to {keys|indirectObject}
GIVE	give {eggs|directObject} to {food|indirectObject}
GIVE	give {eggs|directObject} to {lamp|indirectObject}
GIVE	give {eggs|directObject} to {grate|indirectObject}
GIVE	give {eggs|directObject} to {dragon|indirectObject}
GIVE	give {eggs|directObject} to {rug|indirectObject}
GIVE	give {eggs|directObject} to {persian rug|indirectObject}
GIVE	give {eggs|directObject} to {water|indirectObject}
GIVE	give {eggs|directObject} to {plant|indirectObject}
GIVE	give {eggs|directObject} to {emerald|indirectObject}
GIVE	give {eggs|directObject} to {vase|indirectObject}
GIVE	give {eggs|directObject} to {ming vase|indirectObject}
GIVE	give {eggs|directObject} to {pillow|indirectObject}
GIVE	give {eggs|directObject} to {pyramid|indirectObject}
GIVE	give {eggs|directObject} to {beanstalk|indirectObject}
GIVE	give {eggs|directObject} to {eggs|indirectObject}
GIVE	give {eggs|directObject} to {door|indirectObject}
GIVE	give {eggs|directObject} to {trident|indirectObject}
GIVE	give {eggs|directObject} to {bear|indirectObject}
GIVE	give {eggs|directObject} to {troll|indirectObject}
GIVE	give {eggs|directObject} to {chain|indirectObject}
GIVE	give {eggs|directObject} to {spices|indirectObject}
GIVE	give {eggs|directObject} to {magazine|indirectObject}
GIVE	give {eggs|directObject} to {pearl|indirectObject}
GIVE	give {eggs|directObject} to {jewelry|indirectObject}
GIVE	give {eggs|directObject} to {coins|indirectObject}
GIVE	give {eggs|directObject} to {diamonds|indirectObject}
GIVE	give {eggs|directObject} to {rod|indirectObject}
GIVE	give {eggs|directObject} to {axe|indirectObject}
GIVE	give {eggs|directObject} to {dwarf|indirectObject}
GIVE	give {door|directObject} to {sliver|indirectObject}
GIVE	give {door|directObject} to {bars|indirectObject}
GIVE	give {door|directObject} to {silver bars|indirectObject}
GIVE	give {door|directObject} to {all|indirectObject}
GIVE	give {door|directObject} to {bird|indirectObject}
GIVE	give {door|directObject} to {cage|indirectObject}
GIVE	give {door|directObject} to {wicker cage|indirectObject}
GIVE	give {door|directObject} to {gold nugget|indirectObject}
GIVE	give {door|directObject} to {nugget|indirectObject}
GIVE	give {door|directObject} to {keys|indirectObject}
GIVE	give {door|directObject} to {food|indirectObject}
GIVE	give {door|directObject} to {lamp|indirectObject}
GIVE	give {door|directObject} to {grate|indirectObject}
GIVE	give {door|directObject} to {dragon|indirectObject}
GIVE	give {door|directObject} to {rug|indirectObject}
GIVE	give {door|directObject} to {persian rug|indirectObject}
GIVE	give {door|directObject} to {water|indirectObject}
GIVE	give {door|directObject} to {plant|indirectObject}
GIVE	give {door|directObject} to {emerald|indirectObject}
GIVE	give {door|directObject} to {vase|indirectObject}
GIVE	give {door|directObject} to {ming vase|indirectObject}
GIVE	give {door|directObject} to {pillow|indirectObject}
GIVE	give {door|directObject} to {pyramid|indirectObject}
GIVE	give {door|directObject} to {beanstalk|indirectObject}
GIVE	give {door|directObject} to {eggs|indirectObject}
GIVE	give {door|directObject} to {door|indirectObject}
GIVE	give {door|directObject} to {trident|indirectObject}
GIVE	give {door|directObject} to {bear|indirectObject}
GIVE	give {door|directObject} to {troll|indirectObject}
GIVE	give {door|directObject} to {chain|indirectObject}
GIVE	give {door|directObject} to {spices|indirectObject}
GIVE	give {door|directObject} to {magazine|indirectObject}
GIVE	give {door|directObject} to {pearl|indirectObject}
GIVE	give {door|directObject} to {jewelry|indirectObject}
GIVE	give {door|directObject} to {coins|indirectObject}
GIVE	give {door|directObject} to {diamonds|indirectObject}
GIVE	give {door|directObject} to {rod|indirectObject}
GIVE	give {door|directObject} to {axe|indirectObject}
GIVE	give {door|directObject} to {dwarf|indirectObject}
GIVE	give {trident|directObject} to {sliver|indirectObject}
GIVE	give {trident|directObject} to {bars|indirectObject}
GIVE	give {trident|directObject} to {silver bars|indirectObject}
GIVE	give {trident|directObject} to {all|indirectObject}
GIVE	give {trident|directObject} to {bird|indirectObject}
GIVE	give {trident|directObject} to {cage|indirectObject}
GIVE	give {trident|directObject} to {wicker cage|indirectObject}
GIVE	give {trident|directObject} to {gold nugget|indirectObject}
GIVE	give {trident|directObject} to {nugget|indirectObject}
GIVE	give {trident|directObject} to {keys|indirectObject}
GIVE	give {trident|directObject} to {food|indirectObject}
GIVE	give {trident|directObject} to {lamp|indirectObject}
GIVE	give {trident|directObject} to {grate|indirectObject}
GIVE	give {trident|directObject} to {dragon|indirectObject}
GIVE	give {trident|directObject} to {rug|indirectObject}
GIVE	give {trident|directObject} to {persian rug|indirectObject}
GIVE	give {trident|directObject} to {water|indirectObject}
GIVE	give {trident|directObject} to {plant|indirectObject}
GIVE	give {trident|directObject} to {emerald|indirectObject}
GIVE	give {trident|directObject} to {vase|indirectObject}
GIVE	give {trident|directObject} to {ming vase|indirectObject}
GIVE	give {trident|directObject} to {pillow|indirectObject}
GIVE	give {trident|directObject} to {pyramid|indirectObject}
GIVE	give {trident|directObject} to {beanstalk|indirectObject}
GIVE	give {trident|directObject} to {eggs|indirectObject}
GIVE	give {trident|directObject} to {door|indirectObject}
GIVE	give {trident|directObject} to {trident|indirectObject}
GIVE	give {trident|directObject} to {bear|indirectObject}
GIVE	give {trident|directObject} to {troll|indirectObject}
GIVE	give {trident|directObject} to {chain|indirectObject}
GIVE	give {trident|directObject} to {spices|indirectObject}
GIVE	give {trident|directObject} to {magazine|indirectObject}
GIVE	give {trident|directObject} to {pearl|indirectObject}
GIVE	give {trident|directObject} to {jewelry|indirectObject}
GIVE	give {trident|directObject} to {coins|indirectObject}
GIVE	give {trident|directObject} to {diamonds|indirectObject}
GIVE	give {trident|directObject} to {rod|indirectObject}
GIVE	give {trident|directObject} to {axe|indirectObject}
GIVE	give {trident|directObject} to {dwarf|indirectObject}
GIVE	give {bear|directObject} to {sliver|indirectObject}
GIVE	give {bear|directObject} to {bars|indirectObject}
GIVE	give {bear|directObject} to {silver bars|indirectObject}
GIVE	give {bear|directObject} to {all|indirectObject}
GIVE	give {bear|directObject} to {bird|indirectObject}
GIVE	give {bear|directObject} to {cage|indirectObject}
GIVE	give {bear|directObject} to {wicker cage|indirectObject}
GIVE	give {bear|directObject} to {gold nugget|indirectObject}
GIVE	give {bear|directObject} to {nugget|indirectObject}
GIVE	give {bear|directObject} to {keys|indirectObject}
GIVE	give {bear|directObject} to {food|indirectObject}
GIVE	give {bear|directObject} to {lamp|indirectObject}
GIVE	give {bear|directObject} to {grate|indirectObject}
GIVE	give {bear|directObject} to {dragon|indirectObject}
GIVE	give {bear|directObject} to {rug|indirectObject}
GIVE	give {bear|directObject} to {persian rug|indirectObject}
GIVE	give {bear|directObject} to {water|indirectObject}
GIVE	give {bear|directObject} to {plant|indirectObject}
GIVE	give {bear|directObject} to {emerald|indirectObject}
GIVE	give {bear|directObject} to {vase|indirectObject}
GIVE	give {bear|directObject} to {ming vase|indirectObject}
GIVE	give {bear|directObject} to {pillow|indirectObject}
GIVE	give {bear|directObject} to {pyramid|indirectObject}
GIVE	give {bear|directObject} to {beanstalk|indirectObject}
GIVE	give {bear|directObject} to {eggs|indirectObject}
GIVE	give {bear|directObject} to {door|indirectObject}
GIVE	give {bear|directObject} to {trident|indirectObject}
GIVE	give {bear|directObject} to {bear|indirectObject}
GIVE	give {bear|directObject} to {troll|indirectObject}
GIVE	give {bear|directObject} to {chain|indirectObject}
GIVE	give {bear|directObject} to {spices|indirectObject}
GIVE	give {bear|directObject} to {magazine|indirectObject}
GIVE	give {bear|directObject} to {pearl|indirectObject}
GIVE	give {bear|directObject} to {jewelry|indirectObject}
GIVE	give {bear|directObject} to {coins|indirectObject}
GIVE	give {bear|directObject} to {diamonds|indirectObject}
GIVE	give {bear|directObject} to {rod|indirectObject}
GIVE	give {bear|directObject} to {axe|indirectObject}
GIVE	give {bear|directObject} to {dwarf|indirectObject}
GIVE	give {troll|directObject} to {sliver|indirectObject}
GIVE	give {troll|directObject} to {bars|indirectObject}
GIVE	give {troll|directObject} to {silver bars|indirectObject}
GIVE	give {troll|directObject} to {all|indirectObject}
GIVE	give {troll|directObject} to {bird|indirectObject}
GIVE	give {troll|directObject} to {cage|indirectObject}
GIVE	give {troll|directObject} to {wicker cage|indirectObject}
GIVE	give {troll|directObject} to {gold nugget|indirectObject}
GIVE	give {troll|directObject} to {nugget|indirectObject}
GIVE	give {troll|directObject} to {keys|indirectObject}
GIVE	give {troll|directObject} to {food|indirectObject}
GIVE	give {troll|directObject} to {lamp|indirectObject}
GIVE	give {troll|directObject} to {grate|indirectObject}
GIVE	give {troll|directObject} to {dragon|indirectObject}
GIVE	give {troll|directObject} to {rug|indirectObject}
GIVE	give {troll|directObject} to {persian rug|indirectObject}
GIVE	give {troll|directObject} to {water|indirectObject}
GIVE	give {troll|directObject} to {plant|indirectObject}
GIVE	give {troll|directObject} to {emerald|indirectObject}
GIVE	give {troll|directObject} to {vase|indirectObject}
GIVE	give {troll|directObject} to {ming vase|indirectObject}
GIVE	give {troll|directObject} to {pillow|indirectObject}
GIVE	give {troll|directObject} to {pyramid|indirectObject}
GIVE	give {troll|directObject} to {beanstalk|indirectObject}
GIVE	give {troll|directObject} to {eggs|indirectObject}
GIVE	give {troll|directObject} to {door|indirectObject}
GIVE	give {troll|directObject} to {trident|indirectObject}
GIVE	give {troll|directObject} to {bear|indirectObject}
GIVE	give {troll|directObject} to {troll|indirectObject}
GIVE	give {troll|directObject} to {chain|indirectObject}
GIVE	give {troll|directObject} to {spices|indirectObject}
GIVE	give {troll|directObject} to {magazine|indirectObject}
GIVE	give {troll|directObject} to {pearl|indirectObject}
GIVE	give {troll|directObject} to {jewelry|indirectObject}
GIVE	give {troll|directObject} to {coins|indirectObject}
GIVE	give {troll|directObject} to {diamonds|indirectObject}
GIVE	give {troll|directObject} to {rod|indirectObject}
GIVE	give {troll|directObject} to {axe|indirectObject}
GIVE	give {troll|directObject} to {dwarf|indirectObject}
GIVE	give {chain|directObject} to {sliver|indirectObject}
GIVE	give {chain|directObject} to {bars|indirectObject}
GIVE	give {chain|directObject} to {silver bars|indirectObject}
GIVE	give {chain|directObject} to {all|indirectObject}
GIVE	give {chain|directObject} to {bird|indirectObject}
GIVE	give {chain|directObject} to {cage|indirectObject}
GIVE	give {chain|directObject} to {wicker cage|indirectObject}
GIVE	give {chain|directObject} to {gold nugget|indirectObject}
GIVE	give {chain|directObject} to {nugget|indirectObject}
GIVE	give {chain|directObject} to {keys|indirectObject}
GIVE	give {chain|directObject} to {food|indirectObject}
GIVE	give {chain|directObject} to {lamp|indirectObject}
GIVE	give {chain|directObject} to {grate|indirectObject}
GIVE	give {chain|directObject} to {dragon|indirectObject}
GIVE	give {chain|directObject} to {rug|indirectObject}
GIVE	give {chain|directObject} to {persian rug|indirectObject}
GIVE	give {chain|directObject} to {water|indirectObject}
GIVE	give {chain|directObject} to {plant|indirectObject}
GIVE	give {chain|directObject} to {emerald|indirectObject}
GIVE	give {chain|directObject} to {vase|indirectObject}
GIVE	give {chain|directObject} to {ming vase|indirectObject}
GIVE	give {chain|directObject} to {pillow|indirectObject}
GIVE	give {chain|directObject} to {pyramid|indirectObject}
GIVE	give {chain|directObject} to {beanstalk|indirectObject}
GIVE	give {chain|directObject} to {eggs|indirectObject}
GIVE	give {chain|directObject} to {door|indirectObject}
GIVE	give {chain|directObject} to {trident|indirectObject}
GIVE	give {chain|directObject} to {bear|indirectObject}
GIVE	give {chain|directObject} to {troll|indirectObject}
GIVE	give {chain|directObject} to {chain|indirectObject}
GIVE	give {chain|directObject} to {spices|indirectObject}
GIVE	give {chain|directObject} to {magazine|indirectObject}
GIVE	give {chain|directObject} to {pearl|indirectObject}
GIVE	give {chain|directObject} to {jewelry|indirectObject}
GIVE	give {chain|directObject} to {coins|indirectObject}
GIVE	give {chain|directObject} to {diamonds|indirectObject}
GIVE	give {chain|directObject} to {rod|indirectObject}
GIVE	give {chain|directObject} to {axe|indirectObject}
GIVE	give {chain|directObject} to {dwarf|indirectObject}
GIVE	give {spices|directObject} to {sliver|indirectObject}
GIVE	give {spices|directObject} to {bars|indirectObject}
GIVE	give {spices|directObject} to {silver bars|indirectObject}
GIVE	give {spices|directObject} to {all|indirectObject}
GIVE	give {spices|directObject} to {bird|indirectObject}
GIVE	give {spices|directObject} to {cage|indirectObject}
GIVE	give {spices|directObject} to {wicker cage|indirectObject}
GIVE	give {spices|directObject} to {gold nugget|indirectObject}
GIVE	give {spices|directObject} to {nugget|indirectObject}
GIVE	give {spices|directObject} to {keys|indirectObject}
GIVE	give {spices|directObject} to {food|indirectObject}
GIVE	give {spices|directObject} to {lamp|indirectObject}
GIVE	give {spices|directObject} to {grate|indirectObject}
GIVE	give {spices|directObject} to {dragon|indirectObject}
GIVE	give {spices|directObject} to {rug|indirectObject}
GIVE	give {spices|directObject} to {persian rug|indirectObject}
GIVE	give {spices|directObject} to {water|indirectObject}
GIVE	give {spices|directObject} to {plant|indirectObject}
GIVE	give {spices|directObject} to {emerald|indirectObject}
GIVE	give {spices|directObject} to {vase|indirectObject}
GIVE	give {spices|directObject} to {ming vase|indirectObject}
GIVE	give {spices|directObject} to {pillow|indirectObject}
GIVE	give {spices|directObject} to {pyramid|indirectObject}
GIVE	give {spices|directObject} to {beanstalk|indirectObject}
GIVE	give {spices|directObject} to {eggs|indirectObject}
GIVE	give {spices|directObject} to {door|indirectObject}
GIVE	give {spices|directObject} to {trident|indirectObject}
GIVE	give {spices|directObject} to {bear|indirectObject}
GIVE	give {spices|directObject} to {troll|indirectObject}
GIVE	give {spices|directObject} to {chain|indirectObject}
GIVE	give {spices|directObject} to {spices|indirectObject}
GIVE	give {spices|directObject} to {magazine|indirectObject}
GIVE	give {spices|directObject} to {pearl|indirectObject}
GIVE	give {spices|directObject} to {jewelry|indirectObject}
GIVE	give {spices|directObject} to {coins|indirectObject}
GIVE	give {spices|directObject} to {diamonds|indirectObject}
GIVE	give {spices|directObject} to {rod|indirectObject}
GIVE	give {spices|directObject} to {axe|indirectObject}
GIVE	give {spices|directObject} to {dwarf|indirectObject}
GIVE	give {magazine|directObject} to {sliver|indirectObject}
GIVE	give {magazine|directObject} to {bars|indirectObject}
GIVE	give {magazine|directObject} to {silver bars|indirectObject}
GIVE	give {magazine|directObject} to {all|indirectObject}
GIVE	give {magazine|directObject} to {bird|indirectObject}
GIVE	give {magazine|directObject} to {cage|indirectObject}
GIVE	give {magazine|directObject} to {wicker cage|indirectObject}
GIVE	give {magazine|directObject} to {gold nugget|indirectObject}
GIVE	give {magazine|directObject} to {nugget|indirectObject}
GIVE	give {magazine|directObject} to {keys|indirectObject}
GIVE	give {magazine|directObject} to {food|indirectObject}
GIVE	give {magazine|directObject} to {lamp|indirectObject}
GIVE	give {magazine|directObject} to {grate|indirectObject}
GIVE	give {magazine|directObject} to {dragon|indirectObject}
GIVE	give {magazine|directObject} to {rug|indirectObject}
GIVE	give {magazine|directObject} to {persian rug|indirectObject}
GIVE	give {magazine|directObject} to {water|indirectObject}
GIVE	give {magazine|directObject} to {plant|indirectObject}
GIVE	give {magazine|directObject} to {emerald|indirectObject}
GIVE	give {magazine|directObject} to {vase|indirectObject}
GIVE	give {magazine|directObject} to {ming vase|indirectObject}
GIVE	give {magazine|directObject} to {pillow|indirectObject}
GIVE	give {magazine|directObject} to {pyramid|indirectObject}
GIVE	give {magazine|directObject} to {beanstalk|indirectObject}
GIVE	give {magazine|directObject} to {eggs|indirectObject}
GIVE	give {magazine|directObject} to {door|indirectObject}
GIVE	give {magazine|directObject} to {trident|indirectObject}
GIVE	give {magazine|directObject} to {bear|indirectObject}
GIVE	give {magazine|directObject} to {troll|indirectObject}
GIVE	give {magazine|directObject} to {chain|indirectObject}
GIVE	give {magazine|directObject} to {spices|indirectObject}
GIVE	give {magazine|directObject} to {magazine|indirectObject}
GIVE	give {magazine|directObject} to {pearl|indirectObject}
GIVE	give {magazine|directObject} to {jewelry|indirectObject}
GIVE	give {magazine|directObject} to {coins|indirectObject}
GIVE	give {magazine|directObject} to {diamonds|indirectObject}
GIVE	give {magazine|directObject} to {rod|indirectObject}
GIVE	give {magazine|directObject} to {axe|indirectObject}
GIVE	give {magazine|directObject} to {dwarf|indirectObject}
GIVE	give {pearl|directObject} to {sliver|indirectObject}
GIVE	give {pearl|directObject} to {bars|indirectObject}
GIVE	give {pearl|directObject} to {silver bars|indirectObject}
GIVE	give {pearl|directObject} to {all|indirectObject}
GIVE	give {pearl|directObject} to {bird|indirectObject}
GIVE	give {pearl|directObject} to {cage|indirectObject}
GIVE	give {pearl|directObject} to {wicker cage|indirectObject}
GIVE	give {pearl|directObject} to {gold nugget|indirectObject}
GIVE	give {pearl|directObject} to {nugget|indirectObject}
GIVE	give {pearl|directObject} to {keys|indirectObject}
GIVE	give {pearl|directObject} to {food|indirectObject}
GIVE	give {pearl|directObject} to {lamp|indirectObject}
GIVE	give {pearl|directObject} to {grate|indirectObject}
GIVE	give {pearl|directObject} to {dragon|indirectObject}
GIVE	give {pearl|directObject} to {rug|indirectObject}
GIVE	give {pearl|directObject} to {persian rug|indirectObject}
GIVE	give {pearl|directObject} to {water|indirectObject}
GIVE	give {pearl|directObject} to {plant|indirectObject}
GIVE	give {pearl|directObject} to {emerald|indirectObject}
GIVE	give {pearl|directObject} to {vase|indirectObject}
GIVE	give {pearl|directObject} to {ming vase|indirectObject}
GIVE	give {pearl|directObject} to {pillow|indirectObject}
GIVE	give {pearl|directObject} to {pyramid|indirectObject}
GIVE	give {pearl|directObject} to {beanstalk|indirectObject}
GIVE	give {pearl|directObject} to {eggs|indirectObject}
GIVE	give {pearl|directObject} to {door|indirectObject}
GIVE	give {pearl|directObject} to {trident|indirectObject}
GIVE	give {pearl|directObject} to {bear|indirectObject}
GIVE	give {pearl|directObject} to {troll|indirectObject}
GIVE	give {pearl|directObject} to {chain|indirectObject}
GIVE	give {pearl|directObject} to {spices|indirectObject}
GIVE	give {pearl|directObject} to {magazine|indirectObject}
GIVE	give {pearl|directObject} to {pearl|indirectObject}
GIVE	give {pearl|directObject} to {jewelry|indirectObject}
GIVE	give {pearl|directObject} to {coins|indirectObject}
GIVE	give {pearl|directObject} to {diamonds|indirectObject}
GIVE	give {pearl|directObject} to {rod|indirectObject}
GIVE	give {pearl|directObject} to {axe|indirectObject}
GIVE	give {pearl|directObject} to {dwarf|indirectObject}
GIVE	give {jewelry|directObject} to {sliver|indirectObject}
GIVE	give {jewelry|directObject} to {bars|indirectObject}
GIVE	give {jewelry|directObject} to {silver bars|indirectObject}
GIVE	give {jewelry|directObject} to {all|indirectObject}
GIVE	give {jewelry|directObject} to {bird|indirectObject}
GIVE	give {jewelry|directObject} to {cage|indirectObject}
GIVE	give {jewelry|directObject} to {wicker cage|indirectObject}
GIVE	give {jewelry|directObject} to {gold nugget|indirectObject}
GIVE	give {jewelry|directObject} to {nugget|indirectObject}
GIVE	give {jewelry|directObject} to {keys|indirectObject}
GIVE	give {jewelry|directObject} to {food|indirectObject}
GIVE	give {jewelry|directObject} to {lamp|indirectObject}
GIVE	give {jewelry|directObject} to {grate|indirectObject}
GIVE	give {jewelry|directObject} to {dragon|indirectObject}
GIVE	give {jewelry|directObject} to {rug|indirectObject}
GIVE	give {jewelry|directObject} to {persian rug|indirectObject}
GIVE	give {jewelry|directObject} to {water|indirectObject}
GIVE	give {jewelry|directObject} to {plant|indirectObject}
GIVE	give {jewelry|directObject} to {emerald|indirectObject}
GIVE	give {jewelry|directObject} to {vase|indirectObject}
GIVE	give {jewelry|directObject} to {ming vase|indirectObject}
GIVE	give {jewelry|directObject} to {pillow|indirectObject}
GIVE	give {jewelry|directObject} to {pyramid|indirectObject}
GIVE	give {jewelry|directObject} to {beanstalk|indirectObject}
GIVE	give {jewelry|directObject} to {eggs|indirectObject}
GIVE	give {jewelry|directObject} to {door|indirectObject}
GIVE	give {jewelry|directObject} to {trident|indirectObject}
GIVE	give {jewelry|directObject} to {bear|indirectObject}
GIVE	give {jewelry|directObject} to {troll|indirectObject}
GIVE	give {jewelry|directObject} to {chain|indirectObject}
GIVE	give {jewelry|directObject} to {spices|indirectObject}
GIVE	give {jewelry|directObject} to {magazine|indirectObject}
GIVE	give {jewelry|directObject} to {pearl|indirectObject}
GIVE	give {jewelry|directObject} to {jewelry|indirectObject}
GIVE	give {jewelry|directObject} to {coins|indirectObject}
GIVE	give {jewelry|directObject} to {diamonds|indirectObject}
GIVE	give {jewelry|directObject} to {rod|indirectObject}
GIVE	give {jewelry|directObject} to {axe|indirectObject}
GIVE	give {jewelry|directObject} to {dwarf|indirectObject}
GIVE	give {coins|directObject} to {sliver|indirectObject}
GIVE	give {coins|directObject} to {bars|indirectObject}
GIVE	give {coins|directObject} to {silver bars|indirectObject}
GIVE	give {coins|directObject} to {all|indirectObject}
GIVE	give {coins|directObject} to {bird|indirectObject}
GIVE	give {coins|directObject} to {cage|indirectObject}
GIVE	give {coins|directObject} to {wicker cage|indirectObject}
GIVE	give {coins|directObject} to {gold nugget|indirectObject}
GIVE	give {coins|directObject} to {nugget|indirectObject}
GIVE	give {coins|directObject} to {keys|indirectObject}
GIVE	give {coins|directObject} to {food|indirectObject}
GIVE	give {coins|directObject} to {lamp|indirectObject}
GIVE	give {coins|directObject} to {grate|indirectObject}
GIVE	give {coins|directObject} to {dragon|indirectObject}
GIVE	give {coins|directObject} to {rug|indirectObject}
GIVE	give {coins|directObject} to {persian rug|indirectObject}
GIVE	give {coins|directObject} to {water|indirectObject}
GIVE	give {coins|directObject} to {plant|indirectObject}
GIVE	give {coins|directObject} to {emerald|indirectObject}
GIVE	give {coins|directObject} to {vase|indirectObject}
GIVE	give {coins|directObject} to {ming vase|indirectObject}
GIVE	give {coins|directObject} to {pillow|indirectObject}
GIVE	give {coins|directObject} to {pyramid|indirectObject}
GIVE	give {coins|directObject} to {beanstalk|indirectObject}
GIVE	give {coins|directObject} to {eggs|indirectObject}
GIVE	give {coins|directObject} to {door|indirectObject}
GIVE	give {coins|directObject} to {trident|indirectObject}
GIVE	give {coins|directObject} to {bear|indirectObject}
GIVE	give {coins|directObject} to {troll|indirectObject}
GIVE	give {coins|directObject} to {chain|indirectObject}
GIVE	give {coins|directObject} to {spices|indirectObject}
GIVE	give {coins|directObject} to {magazine|indirectObject}
GIVE	give {coins|directObject} to {pearl|indirectObject}
GIVE	give {coins|directObject} to {jewelry|indirectObject}
GIVE	give {coins|directObject} to {coins|indirectObject}
GIVE	give {coins|directObject} to {diamonds|indirectObject}
GIVE	give {coins|directObject} to {rod|indirectObject}
GIVE	give {coins|directObject} to {axe|indirectObject}
GIVE	give {coins|directObject} to {dwarf|indirectObject}
GIVE	give {diamonds|directObject} to {sliver|indirectObject}
GIVE	give {diamonds|directObject} to {bars|indirectObject}
GIVE	give {diamonds|directObject} to {silver bars|indirectObject}
GIVE	give {diamonds|directObject} to {all|indirectObject}
GIVE	give {diamonds|directObject} to {bird|indirectObject}
GIVE	give {diamonds|directObject} to {cage|indirectObject}
GIVE	give {diamonds|directObject} to {wicker cage|indirectObject}
GIVE	give {diamonds|directObject} to {gold nugget|indirectObject}
GIVE	give {diamonds|directObject} to {nugget|indirectObject}
GIVE	give {diamonds|directObject} to {keys|indirectObject}
GIVE	give {diamonds|directObject} to {food|indirectObject}
GIVE	give {diamonds|directObject} to {lamp|indirectObject}
GIVE	give {diamonds|directObject} to {grate|indirectObject}
GIVE	give {diamonds|directObject} to {dragon|indirectObject}
GIVE	give {diamonds|directObject} to {rug|indirectObject}
GIVE	give {diamonds|directObject} to {persian rug|indirectObject}
GIVE	give {diamonds|directObject} to {water|indirectObject}
GIVE	give {diamonds|directObject} to {plant|indirectObject}
GIVE	give {diamonds|directObject} to {emerald|indirectObject}
GIVE	give {diamonds|directObject} to {vase|indirectObject}
GIVE	give {diamonds|directObject} to {ming vase|indirectObject}
GIVE	give {diamonds|directObject} to {pillow|indirectObject}
GIVE	give {diamonds|directObject} to {pyramid|indirectObject}
GIVE	give {diamonds|directObject} to {beanstalk|indirectObject}
GIVE	give {diamonds|directObject} to {eggs|indirectObject}
GIVE	give {diamonds|directObject} to {door|indirectObject}
GIVE	give {diamonds|directObject} to {trident|indirectObject}
GIVE	give {diamonds|directObject} to {bear|indirectObject}
GIVE	give {diamonds|directObject} to {troll|indirectObject}
GIVE	give {diamonds|directObject} to {chain|indirectObject}
GIVE	give {diamonds|directObject} to {spices|indirectObject}
GIVE	give {diamonds|directObject} to {magazine|indirectObject}
GIVE	give {diamonds|directObject} to {pearl|indirectObject}
GIVE	give {diamonds|directObject} to {jewelry|indirectObject}
GIVE	give {diamonds|directObject} to {coins|indirectObject}
GIVE	give {diamonds|directObject} to {diamonds|indirectObject}
GIVE	give {diamonds|directObject} to {rod|indirectObject}
GIVE	give {diamonds|directObject} to {axe|indirectObject}
GIVE	give {diamonds|directObject} to {dwarf|indirectObject}
GIVE	give {rod|directObject} to {sliver|indirectObject}
GIVE	give {rod|directObject} to {bars|indirectObject}
GIVE	give {rod|directObject} to {silver bars|indirectObject}
GIVE	give {rod|directObject} to {all|indirectObject}
GIVE	give {rod|directObject} to {bird|indirectObject}
GIVE	give {rod|directObject} to {cage|indirectObject}
GIVE	give {rod|directObject} to {wicker cage|indirectObject}
GIVE	give {rod|directObject} to {gold nugget|indirectObject}
GIVE	give {rod|directObject} to {nugget|indirectObject}
GIVE	give {rod|directObject} to {keys|indirectObject}
GIVE	give {rod|directObject} to {food|indirectObject}
GIVE	give {rod|directObject} to {lamp|indirectObject}
GIVE	give {rod|directObject} to {grate|indirectObject}
GIVE	give {rod|directObject} to {dragon|indirectObject}
GIVE	give {rod|directObject} to {rug|indirectObject}
GIVE	give {rod|directObject} to {persian rug|indirectObject}
GIVE	give {rod|directObject} to {water|indirectObject}
GIVE	give {rod|directObject} to {plant|indirectObject}
GIVE	give {rod|directObject} to {emerald|indirectObject}
GIVE	give {rod|directObject} to {vase|indirectObject}
GIVE	give {rod|directObject} to {ming vase|indirectObject}
GIVE	give {rod|directObject} to {pillow|indirectObject}
GIVE	give {rod|directObject} to {pyramid|indirectObject}
GIVE	give {rod|directObject} to {beanstalk|indirectObject}
GIVE	give {rod|directObject} to {eggs|indirectObject}
GIVE	give {rod|directObject} to {door|indirectObject}
GIVE	give {rod|directObject} to {trident|indirectObject}
GIVE	give {rod|directObject} to {bear|indirectObject}
GIVE	give {rod|directObject} to {troll|indirectObject}
GIVE	give {rod|directObject} to {chain|indirectObject}
GIVE	give {rod|directObject} to {spices|indirectObject}
GIVE	give {rod|directObject} to {magazine|indirectObject}
GIVE	give {rod|directObject} to {pearl|indirectObject}
GIVE	give {rod|directObject} to {jewelry|indirectObject}
GIVE	give {rod|directObject} to {coins|indirectObject}
GIVE	give {rod|directObject} to {diamonds|indirectObject}
GIVE	give {rod|directObject} to {rod|indirectObject}
GIVE	give {rod|directObject} to {axe|indirectObject}
GIVE	give {rod|directObject} to {dwarf|indirectObject}
GIVE	give {axe|directObject} to {sliver|indirectObject}
GIVE	give {axe|directObject} to {bars|indirectObject}
GIVE	give {axe|directObject} to {silver bars|indirectObject}
GIVE	give {axe|directObject} to {all|indirectObject}
GIVE	give {axe|directObject} to {bird|indirectObject}
GIVE	give {axe|directObject} to {cage|indirectObject}
GIVE	give {axe|directObject} to {wicker cage|indirectObject}
GIVE	give {axe|directObject} to {gold nugget|indirectObject}
GIVE	give {axe|directObject} to {nugget|indirectObject}
GIVE	give {axe|directObject} to {keys|indirectObject}
GIVE	give {axe|directObject} to {food|indirectObject}
GIVE	give {axe|directObject} to {lamp|indirectObject}
GIVE	give {axe|directObject} to {grate|indirectObject}
GIVE	give {axe|directObject} to {dragon|indirectObject}
GIVE	give {axe|directObject} to {rug|indirectObject}
GIVE	give {axe|directObject} to {persian rug|indirectObject}
GIVE	give {axe|directObject} to {water|indirectObject}
GIVE	give {axe|directObject} to {plant|indirectObject}
GIVE	give {axe|directObject} to {emerald|indirectObject}
GIVE	give {axe|directObject} to {vase|indirectObject}
GIVE	give {axe|directObject} to {ming vase|indirectObject}
GIVE	give {axe|directObject} to {pillow|indirectObject}
GIVE	give {axe|directObject} to {pyramid|indirectObject}
GIVE	give {axe|directObject} to {beanstalk|indirectObject}
GIVE	give {axe|directObject} to {eggs|indirectObject}
GIVE	give {axe|directObject} to {door|indirectObject}
GIVE	give {axe|directObject} to {trident|indirectObject}
GIVE	give {axe|directObject} to {bear|indirectObject}
GIVE	give {axe|directObject} to {troll|indirectObject}
GIVE	give {axe|directObject} to {chain|indirectObject}
GIVE	give {axe|directObject} to {spices|indirectObject}
GIVE	give {axe|directObject} to {magazine|indirectObject}
GIVE	give {axe|directObject} to {pearl|indirectObject}
GIVE	give {axe|directObject} to {jewelry|indirectObject}
GIVE	give {axe|directObject} to {coins|indirectObject}
GIVE	give {axe|directObject} to {diamonds|indirectObject}
GIVE	give {axe|directObject} to {rod|indirectObject}
GIVE	give {axe|directObject} to {axe|indirectObject}
GIVE	give {axe|directObject} to {dwarf|indirectObject}
GIVE	give {dwarf|directObject} to {sliver|indirectObject}
GIVE	give {dwarf|directObject} to {bars|indirectObject}
GIVE	give {dwarf|directObject} to {silver bars|indirectObject}
GIVE	give {dwarf|directObject} to {all|indirectObject}
GIVE	give {dwarf|directObject} to {bird|indirectObject}
GIVE	give {dwarf|directObject} to {cage|indirectObject}
GIVE	give {dwarf|directObject} to {wicker cage|indirectObject}
GIVE	give {dwarf|directObject} to {gold nugget|indirectObject}
GIVE	give {dwarf|directObject} to {nugget|indirectObject}
GIVE	give {dwarf|directObject} to {keys|indirectObject}
GIVE	give {dwarf|directObject} to {food|indirectObject}
GIVE	give {dwarf|directObject} to {lamp|indirectObject}
GIVE	give {dwarf|directObject} to {grate|indirectObject}
GIVE	give {dwarf|directObject} to {dragon|indirectObject}
GIVE	give {dwarf|directObject} to {rug|indirectObject}
GIVE	give {dwarf|directObject} to {persian rug|indirectObject}
GIVE	give {dwarf|directObject} to {water|indirectObject}
GIVE	give {dwarf|directObject} to {plant|indirectObject}
GIVE	give {dwarf|directObject} to {emerald|indirectObject}
GIVE	give {dwarf|directObject} to {vase|indirectObject}
GIVE	give {dwarf|directObject} to {ming vase|indirectObject}
GIVE	give {dwarf|directObject} to {pillow|indirectObject}
GIVE	give {dwarf|directObject} to {pyramid|indirectObject}
GIVE	give {dwarf|directObject} to {beanstalk|indirectObject}
GIVE	give {dwarf|directObject} to {eggs|indirectObject}
GIVE	give {dwarf|directObject} to {door|indirectObject}
GIVE	give {dwarf|directObject} to {trident|indirectObject}
GIVE	give {dwarf|directObject} to {bear|indirectObject}
GIVE	give {dwarf|directObject} to {troll|indirectObject}
GIVE	give {dwarf|directObject} to {chain|indirectObject}
GIVE	give {dwarf|directObject} to {spices|indirectObject}
GIVE	give {dwarf|directObject} to {magazine|indirectObject}
GIVE	give {dwarf|directObject} to {pearl|indirectObject}
GIVE	give {dwarf|directObject} to {jewelry|indirectObject}
GIVE	give {dwarf|directObject} to {coins|indirectObject}
GIVE	give {dwarf|directObject} to {diamonds|indirectObject}
GIVE	give {dwarf|directObject} to {rod|indirectObject}
GIVE	give {dwarf|directObject} to {axe|indirectObject}
GIVE	give {dwarf|directObject} to {dwarf|indirectObject}
THROW	throw {axe|directObject} at {sliver|indirectObject}
THROW	throw {axe|directObject} at {bars|indirectObject}
THROW	throw {axe|directObject} at {silver bars|indirectObject}
THROW	throw {axe|directObject} at {all|indirectObject}
THROW	throw {axe|directObject} at {bird|indirectObject}
THROW	throw {axe|directObject} at {cage|indirectObject}
THROW	throw {axe|directObject} at {wicker cage|indirectObject}
THROW	throw {axe|directObject} at {gold nugget|indirectObject}
THROW	throw {axe|directObject} at {nugget|indirectObject}
THROW	throw {axe|directObject} at {keys|indirectObject}
THROW	throw {axe|directObject} at {food|indirectObject}
THROW	throw {axe|directObject} at {lamp|indirectObject}
THROW	throw {axe|directObject} at {grate|indirectObject}
THROW	throw {axe|directObject} at {dragon|indirectObject}
THROW	throw {axe|directObject} at {rug|indirectObject}
THROW	throw {axe|directObject} at {persian rug|indirectObject}
THROW	throw {axe|directObject} at {water|indirectObject}
THROW	throw {axe|directObject} at {plant|indirectObject}
THROW	throw {axe|directObject} at {emerald|indirectObject}
THROW	throw {axe|directObject} at {vase|indirectObject}
THROW	throw {axe|directObject} at {ming vase|indirectObject}
THROW	throw {axe|directObject} at {pillow|indirectObject}
THROW	throw {axe|directObject} at {pyramid|indirectObject}
THROW	throw {axe|directObject} at {beanstalk|indirectObject}
THROW	throw {axe|directObject} at {eggs|indirectObject}
THROW	throw {axe|directObject} at {door|indirectObject}
THROW	throw {axe|directObject} at {trident|indirectObject}
THROW	throw {axe|directObject} at {bear|indirectObject}
THROW	throw {axe|directObject} at {troll|indirectObject}
THROW	throw {axe|directObject} at {chain|indirectObject}
THROW	throw {axe|directObject} at {spices|indirectObject}
THROW	throw {axe|directObject} at {magazine|indirectObject}
THROW	throw {axe|directObject} at {pearl|indirectObject}
THROW	throw {axe|directObject} at {jewelry|indirectObject}
THROW	throw {axe|directObject} at {coins|indirectObject}
THROW	throw {axe|directObject} at {diamonds|indirectObject}
THROW	throw {axe|directObject} at {rod|indirectObject}
THROW	throw {axe|directObject} at {axe|indirectObject}
THROW	throw {axe|directObject} at {dwarf|indirectObject}
GET	get {sliver|directObject}
GET	get {bars|directObject}
GET	get {silver bars|directObject}
GET	get {all|directObject}
GET	get {bird|directObject}
GET	get {cage|directObject}
GET	get {wicker cage|directObject}
GET	get {gold nugget|directObject}
GET	get {nugget|directObject}
GET	get {keys|directObject}
GET	get {food|directObject}
GET	get {lamp|directObject}
GET	get {grate|directObject}
GET	get {dragon|directObject}
GET	get {rug|directObject}
GET	get {persian rug|directObject}
GET	get {water|directObject}
GET	get {plant|directObject}
GET	get {emerald|directObject}
GET	get {vase|directObject}
GET	get {ming vase|directObject}
GET	get {pillow|directObject}
GET	get {pyramid|directObject}
GET	get {beanstalk|directObject}
GET	get {eggs|directObject}
GET	get {door|directObject}
GET	get {trident|directObject}
GET	get {bear|directObject}
GET	get {troll|directObject}
GET	get {chain|directObject}
GET	get {spices|directObject}
GET	get {magazine|directObject}
GET	get {pearl|directObject}
GET	get {jewelry|directObject}
GET	get {coins|directObject}
GET	get {diamonds|directObject}
GET	get {rod|directObject}
GET	get {axe|directObject}
GET	get {dwarf|directObject}
TAKE	take {sliver|directObject}
TAKE	take {bars|directObject}
TAKE	take {silver bars|directObject}
TAKE	take {all|directObject}
TAKE	take {bird|directObject}
TAKE	take {cage|directObject}
TAKE	take {wicker cage|directObject}
TAKE	take {gold nugget|directObject}
TAKE	take {nugget|directObject}
TAKE	take {keys|directObject}
TAKE	take {food|directObject}
TAKE	take {lamp|directObject}
TAKE	take {grate|directObject}
TAKE	take {dragon|directObject}
TAKE	take {rug|directObject}
TAKE	take {persian rug|directObject}
TAKE	take {water|directObject}
TAKE	take {plant|directObject}
TAKE	take {emerald|directObject}
TAKE	take {vase|directObject}
TAKE	take {ming vase|directObject}
TAKE	take {pillow|directObject}
TAKE	take {pyramid|directObject}
TAKE	take {beanstalk|directObject}
TAKE	take {eggs|directObject}
TAKE	take {door|directObject}
TAKE	take {trident|directObject}
TAKE	take {bear|directObject}
TAKE	take {troll|directObject}
TAKE	take {chain|directObject}
TAKE	take {spices|directObject}
TAKE	take {magazine|directObject}
TAKE	take {pearl|directObject}
TAKE	take {jewelry|directObject}
TAKE	take {coins|directObject}
TAKE	take {diamonds|directObject}
TAKE	take {rod|directObject}
TAKE	take {axe|directObject}
TAKE	take {dwarf|directObject}
TAKE	grab {sliver|directObject}
TAKE	grab {bars|directObject}
TAKE	grab {silver bars|directObject}
TAKE	grab {all|directObject}
TAKE	grab {bird|directObject}
TAKE	grab {cage|directObject}
TAKE	grab {wicker cage|directObject}
TAKE	grab {gold nugget|directObject}
TAKE	grab {nugget|directObject}
TAKE	grab {keys|directObject}
TAKE	grab {food|directObject}
TAKE	grab {lamp|directObject}
TAKE	grab {grate|directObject}
TAKE	grab {dragon|directObject}
TAKE	grab {rug|directObject}
TAKE	grab {persian rug|directObject}
TAKE	grab {water|directObject}
TAKE	grab {plant|directObject}
TAKE	grab {emerald|directObject}
TAKE	grab {vase|directObject}
TAKE	grab {ming vase|directObject}
TAKE	grab {pillow|directObject}
TAKE	grab {pyramid|directObject}
TAKE	grab {beanstalk|directObject}
TAKE	grab {eggs|directObject}
TAKE	grab {door|directObject}
TAKE	grab {trident|directObject}
TAKE	grab {bear|directObject}
TAKE	grab {troll|directObject}
TAKE	grab {chain|directObject}
TAKE	grab {spices|directObject}
TAKE	grab {magazine|directObject}
TAKE	grab {pearl|directObject}
TAKE	grab {jewelry|directObject}
TAKE	grab {coins|directObject}
TAKE	grab {diamonds|directObject}
TAKE	grab {rod|directObject}
TAKE	grab {axe|directObject}
TAKE	grab {dwarf|directObject}
DROP	drop {sliver|directObject}
DROP	drop {bars|directObject}
DROP	drop {silver bars|directObject}
DROP	drop {all|directObject}
DROP	drop {bird|directObject}
DROP	drop {cage|directObject}
DROP	drop {wicker cage|directObject}
DROP	drop {gold nugget|directObject}
DROP	drop {nugget|directObject}
DROP	drop {keys|directObject}
DROP	drop {food|directObject}
DROP	drop {lamp|directObject}
DROP	drop {grate|directObject}
DROP	drop {dragon|directObject}
DROP	drop {rug|directObject}
DROP	drop {persian rug|directObject}
DROP	drop {water|directObject}
DROP	drop {plant|directObject}
DROP	drop {emerald|directObject}
DROP	drop {vase|directObject}
DROP	drop {ming vase|directObject}
DROP	drop {pillow|directObject}
DROP	drop {pyramid|directObject}
DROP	drop {beanstalk|directObject}
DROP	drop {eggs|directObject}
DROP	drop {door|directObject}
DROP	drop {trident|directObject}
DROP	drop {bear|directObject}
DROP	drop {troll|directObject}
DROP	drop {chain|directObject}
DROP	drop {spices|directObject}
DROP	drop {magazine|directObject}
DROP	drop {pearl|directObject}
DROP	drop {jewelry|directObject}
DROP	drop {coins|directObject}
DROP	drop {diamonds|directObject}
DROP	drop {rod|directObject}
DROP	drop {axe|directObject}
DROP	drop {dwarf|directObject}
OPEN	open {sliver|directObject}
OPEN	open {bars|directObject}
OPEN	open {silver bars|directObject}
OPEN	open {all|directObject}
OPEN	open {bird|directObject}
OPEN	open {cage|directObject}
OPEN	open {wicker cage|directObject}
OPEN	open {gold nugget|directObject}
OPEN	open {nugget|directObject}
OPEN	open {keys|directObject}
OPEN	open {food|directObject}
OPEN	open {lamp|directObject}
OPEN	open {grate|directObject}
OPEN	open {dragon|directObject}
OPEN	open {rug|directObject}
OPEN	open {persian rug|directObject}
OPEN	open {water|directObject}
OPEN	open {plant|directObject}
OPEN	open {emerald|directObject}
OPEN	open {vase|directObject}
OPEN	open {ming vase|directObject}
OPEN	open {pillow|directObject}
OPEN	open {pyramid|directObject}
OPEN	open {beanstalk|directObject}
OPEN	open {eggs|directObject}
OPEN	open {door|directObject}
OPEN	open {trident|directObject}
OPEN	open {bear|directObject}
OPEN	open {troll|directObject}
OPEN	open {chain|directObject}
OPEN	open {spices|directObject}
OPEN	open {magazine|directObject}
OPEN	open {pearl|directObject}
OPEN	open {jewelry|directObject}
OPEN	open {coins|directObject}
OPEN	open {diamonds|directObject}
OPEN	open {rod|directObject}
OPEN	open {axe|directObject}
OPEN	open {dwarf|directObject}
LIGHT	light {sliver|directObject}
LIGHT	light {bars|directObject}
LIGHT	light {silver bars|directObject}
LIGHT	light {all|directObject}
LIGHT	light {bird|directObject}
LIGHT	light {cage|directObject}
LIGHT	light {wicker cage|directObject}
LIGHT	light {gold nugget|directObject}
LIGHT	light {nugget|directObject}
LIGHT	light {keys|directObject}
LIGHT	light {food|directObject}
LIGHT	light {lamp|directObject}
LIGHT	light {grate|directObject}
LIGHT	light {dragon|directObject}
LIGHT	light {rug|directObject}
LIGHT	light {persian rug|directObject}
LIGHT	light {water|directObject}
LIGHT	light {plant|directObject}
LIGHT	light {emerald|directObject}
LIGHT	light {vase|directObject}
LIGHT	light {ming vase|directObject}
LIGHT	light {pillow|directObject}
LIGHT	light {pyramid|directObject}
LIGHT	light {beanstalk|directObject}
LIGHT	light {eggs|directObject}
LIGHT	light {door|directObject}
LIGHT	light {trident|directObject}
LIGHT	light {bear|directObject}
LIGHT	light {troll|directObject}
LIGHT	light {chain|directObject}
LIGHT	light {spices|directObject}
LIGHT	light {magazine|directObject}
LIGHT	light {pearl|directObject}
LIGHT	light {jewelry|directObject}
LIGHT	light {coins|directObject}
LIGHT	light {diamonds|directObject}
LIGHT	light {rod|directObject}
LIGHT	light {axe|directObject}
LIGHT	light {dwarf|directObject}
LIGHT	turn on {sliver|directObject}
LIGHT	turn on {bars|directObject}
LIGHT	turn on {silver bars|directObject}
LIGHT	turn on {all|directObject}
LIGHT	turn on {bird|directObject}
LIGHT	turn on {cage|directObject}
LIGHT	turn on {wicker cage|directObject}
LIGHT	turn on {gold nugget|directObject}
LIGHT	turn on {nugget|directObject}
LIGHT	turn on {keys|directObject}
LIGHT	turn on {food|directObject}
LIGHT	turn on {lamp|directObject}
LIGHT	turn on {grate|directObject}
LIGHT	turn on {dragon|directObject}
LIGHT	turn on {rug|directObject}
LIGHT	turn on {persian rug|directObject}
LIGHT	turn on {water|directObject}
LIGHT	turn on {plant|directObject}
LIGHT	turn on {emerald|directObject}
LIGHT	turn on {vase|directObject}
LIGHT	turn on {ming vase|directObject}
LIGHT	turn on {pillow|directObject}
LIGHT	turn on {pyramid|directObject}
LIGHT	turn on {beanstalk|directObject}
LIGHT	turn on {eggs|directObject}
LIGHT	turn on {door|directObject}
LIGHT	turn on {trident|directObject}
LIGHT	turn on {bear|directObject}
LIGHT	turn on {troll|directObject}
LIGHT	turn on {chain|directObject}
LIGHT	turn on {spices|directObject}
LIGHT	turn on {magazine|directObject}
LIGHT	turn on {pearl|directObject}
LIGHT	turn on {jewelry|directObject}
LIGHT	turn on {coins|directObject}
LIGHT	turn on {diamonds|directObject}
LIGHT	turn on {rod|directObject}
LIGHT	turn on {axe|directObject}
LIGHT	turn on {dwarf|directObject}
KILL	kill {sliver|directObject}
KILL	kill {bars|directObject}
KILL	kill {silver bars|directObject}
KILL	kill {all|directObject}
KILL	kill {bird|directObject}
KILL	kill {cage|directObject}
KILL	kill {wicker cage|directObject}
KILL	kill {gold nugget|directObject}
KILL	kill {nugget|directObject}
KILL	kill {keys|directObject}
KILL	kill {food|directObject}
KILL	kill {lamp|directObject}
KILL	kill {grate|directObject}
KILL	kill {dragon|directObject}
KILL	kill {rug|directObject}
KILL	kill {persian rug|directObject}
KILL	kill {water|directObject}
KILL	kill {plant|directObject}
KILL	kill {emerald|directObject}
KILL	kill {vase|directObject}
KILL	kill {ming vase|directObject}
KILL	kill {pillow|directObject}
KILL	kill {pyramid|directObject}
KILL	kill {beanstalk|directObject}
KILL	kill {eggs|directObject}
KILL	kill {door|directObject}
KILL	kill {trident|directObject}
KILL	kill {bear|directObject}
KILL	kill {troll|directObject}
KILL	kill {chain|directObject}
KILL	kill {spices|directObject}
KILL	kill {magazine|directObject}
KILL	kill {pearl|directObject}
KILL	kill {jewelry|directObject}
KILL	kill {coins|directObject}
KILL	kill {diamonds|directObject}
KILL	kill {rod|directObject}
KILL	kill {axe|directObject}
KILL	kill {dwarf|directObject}
FILL	fill {sliver|directObject}
FILL	fill {bars|directObject}
FILL	fill {silver bars|directObject}
FILL	fill {all|directObject}
FILL	fill {bird|directObject}
FILL	fill {cage|directObject}
FILL	fill {wicker cage|directObject}
FILL	fill {gold nugget|directObject}
FILL	fill {nugget|directObject}
FILL	fill {keys|directObject}
FILL	fill {food|directObject}
FILL	fill {lamp|directObject}
FILL	fill {grate|directObject}
FILL	fill {dragon|directObject}
FILL	fill {rug|directObject}
FILL	fill {persian rug|directObject}
FILL	fill {water|directObject}
FILL	fill {plant|directObject}
FILL	fill {emerald|directObject}
FILL	fill {vase|directObject}
FILL	fill {ming vase|directObject}
FILL	fill {pillow|directObject}
FILL	fill {pyramid|directObject}
FILL	fill {beanstalk|directObject}
FILL	fill {eggs|directObject}
FILL	fill {door|directObject}
FILL	fill {trident|directObject}
FILL	fill {bear|directObject}
FILL	fill {troll|directObject}
FILL	fill {chain|directObject}
FILL	fill {spices|directObject}
FILL	fill {magazine|directObject}
FILL	fill {pearl|directObject}
FILL	fill {jewelry|directObject}
FILL	fill {coins|directObject}
FILL	fill {diamonds|directObject}
FILL	fill {rod|directObject}
FILL	fill {axe|directObject}
FILL	fill {dwarf|directObject}
CLIMB	climb {sliver|directObject}
CLIMB	climb {bars|directObject}
CLIMB	climb {silver bars|directObject}
CLIMB	climb {all|directObject}
CLIMB	climb {bird|directObject}
CLIMB	climb {cage|directObject}
CLIMB	climb {wicker cage|directObject}
CLIMB	climb {gold nugget|directObject}
CLIMB	climb {nugget|directObject}
CLIMB	climb {keys|directObject}
CLIMB	climb {food|directObject}
CLIMB	climb {lamp|directObject}
CLIMB	climb {grate|directObject}
CLIMB	climb {dragon|directObject}
CLIMB	climb {rug|directObject}
CLIMB	climb {persian rug|directObject}
CLIMB	climb {water|directObject}
CLIMB	climb {plant|directObject}
CLIMB	climb {emerald|directObject}
CLIMB	climb {vase|directObject}
CLIMB	climb {ming vase|directObject}
CLIMB	climb {pillow|directObject}
CLIMB	climb {pyramid|directObject}
CLIMB	climb {beanstalk|directObject}
CLIMB	climb {eggs|directObject}
CLIMB	climb {door|directObject}
CLIMB	climb {trident|directObject}
CLIMB	climb {bear|directObject}
CLIMB	climb {troll|directObject}
CLIMB	climb {chain|directObject}
CLIMB	climb {spices|directObject}
CLIMB	climb {magazine|directObject}
CLIMB	climb {pearl|directObject}
CLIMB	climb {jewelry|directObject}
CLIMB	climb {coins|directObject}
CLIMB	climb {diamonds|directObject}
CLIMB	climb {rod|directObject}
CLIMB	climb {axe|directObject}
CLIMB	climb {dwarf|directObject}
WAVE	wave {sliver|directObject}
WAVE	wave {bars|directObject}
WAVE	wave {silver bars|directObject}
WAVE	wave {all|directObject}
WAVE	wave {bird|directObject}
WAVE	wave {cage|directObject}
WAVE	wave {wicker cage|directObject}
WAVE	wave {gold nugget|directObject}
WAVE	wave {nugget|directObject}
WAVE	wave {keys|directObject}
WAVE	wave {food|directObject}
WAVE	wave {lamp|directObject}
WAVE	wave {grate|directObject}
WAVE	wave {dragon|directObject}
WAVE	wave {rug|directObject}
WAVE	wave {persian rug|directObject}
WAVE	wave {water|directObject}
WAVE	wave {plant|directObject}
WAVE	wave {emerald|directObject}
WAVE	wave {vase|directObject}
WAVE	wave {ming vase|directObject}
WAVE	wave {pillow|directObject}
WAVE	wave {pyramid|directObject}
WAVE	wave {beanstalk|directObject}
WAVE	wave {eggs|directObject}
WAVE	wave {door|directObject}
WAVE	wave {trident|directObject}
WAVE	wave {bear|directObject}
WAVE	wave {troll|directObject}
WAVE	wave {chain|directObject}
WAVE	wave {spices|directObject}
WAVE	wave {magazine|directObject}
WAVE	wave {pearl|directObject}
WAVE	wave {jewelry|directObject}
WAVE	wave {coins|directObject}
WAVE	wave {diamonds|directObject}
WAVE	wave {rod|directObject}
WAVE	wave {axe|directObject}
WAVE	wave {dwarf|directObject}
OIL	oil {sliver|directObject}
OIL	oil {bars|directObject}
OIL	oil {silver bars|directObject}
OIL	oil {all|directObject}
OIL	oil {bird|directObject}
OIL	oil {cage|directObject}
OIL	oil {wicker cage|directObject}
OIL	oil {gold nugget|directObject}
OIL	oil {nugget|directObject}
OIL	oil {keys|directObject}
OIL	oil {food|directObject}
OIL	oil {lamp|directObject}
OIL	oil {grate|directObject}
OIL	oil {dragon|directObject}
OIL	oil {rug|directObject}
OIL	oil {persian rug|directObject}
OIL	oil {water|directObject}
OIL	oil {plant|directObject}
OIL	oil {emerald|directObject}
OIL	oil {vase|directObject}
OIL	oil {ming vase|directObject}
OIL	oil {pillow|directObject}
OIL	oil {pyramid|directObject}
OIL	oil {beanstalk|directObject}
OIL	oil {eggs|directObject}
OIL	oil {door|directObject}
OIL	oil {trident|directObject}
OIL	oil {bear|directObject}
OIL	oil {troll|directObject}
OIL	oil {chain|directObject}
OIL	oil {spices|directObject}
OIL	oil {magazine|directObject}
OIL	oil {pearl|directObject}
OIL	oil {jewelry|directObject}
OIL	oil {coins|directObject}
OIL	oil {diamonds|directObject}
OIL	oil {rod|directObject}
OIL	oil {axe|directObject}
OIL	oil {dwarf|directObject}
GIVE	give {sliver|directObject}
GIVE	give {bars|directObject}
GIVE	give {silver bars|directObject}
GIVE	give {all|directObject}
GIVE	give {bird|directObject}
GIVE	give {cage|directObject}
GIVE	give {wicker cage|directObject}
GIVE	give {gold nugget|directObject}
GIVE	give {nugget|directObject}
GIVE	give {keys|directObject}
GIVE	give {food|directObject}
GIVE	give {lamp|directObject}
GIVE	give {grate|directObject}
GIVE	give {dragon|directObject}
GIVE	give {rug|directObject}
GIVE	give {persian rug|directObject}
GIVE	give {water|directObject}
GIVE	give {plant|directObject}
GIVE	give {emerald|directObject}
GIVE	give {vase|directObject}
GIVE	give {ming vase|directObject}
GIVE	give {pillow|directObject}
GIVE	give {pyramid|directObject}
GIVE	give {beanstalk|directObject}
GIVE	give {eggs|directObject}
GIVE	give {door|directObject}
GIVE	give {trident|directObject}
GIVE	give {bear|directObject}
GIVE	give {troll|directObject}
GIVE	give {chain|directObject}
GIVE	give {spices|directObject}
GIVE	give {magazine|directObject}
GIVE	give {pearl|directObject}
GIVE	give {jewelry|directObject}
GIVE	give {coins|directObject}
GIVE	give {diamonds|directObject}
GIVE	give {rod|directObject}
GIVE	give {axe|directObject}
GIVE	give {dwarf|directObject}
PLUGH	plugh
PLUGH	plug
XYZZY	xyzzy
XYZZY	x y z z y
XYZZY	ex why zee zee why
XYZZY	shazam
YES	yes
YES	yep
YES	yeah
NO	no
NO	nope
NO	not a chance
PLOVER	plover
BLAST	blast
FEE	fee
FIE	fie
FOE	foe
FOO	foo
ENTER	enter
ENTER	in
ENTER	go in
OUT	out
OUT	go out
OUT	exit
INVENTORY	inventory
INVENTORY	backpack
INVENTORY	carrying
INVENTORY	what am i carrying
