//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.20 at 10:17:55 AM EDT 
//


package com.ups.xolt.codesamples.response.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DeliveryDetailsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DeliveryDetailsType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="DeliveryDate" type="{}DateTime" minOccurs="0"/&gt;
 *         &lt;element name="ServiceCenter" type="{}ServiceCenterType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DeliveryDetailsType", propOrder = {
    "deliveryDate",
    "serviceCenter"
})
public class DeliveryDetailsType {

    @XmlElement(name = "DeliveryDate")
    protected DateTime deliveryDate;
    @XmlElement(name = "ServiceCenter")
    protected ServiceCenterType serviceCenter;

    /**
     * Gets the value of the deliveryDate property.
     * 
     * @return
     *     possible object is
     *     {@link DateTime }
     *     
     */
    public DateTime getDeliveryDate() {
        return deliveryDate;
    }

    /**
     * Sets the value of the deliveryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTime }
     *     
     */
    public void setDeliveryDate(DateTime value) {
        this.deliveryDate = value;
    }

    /**
     * Gets the value of the serviceCenter property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceCenterType }
     *     
     */
    public ServiceCenterType getServiceCenter() {
        return serviceCenter;
    }

    /**
     * Sets the value of the serviceCenter property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceCenterType }
     *     
     */
    public void setServiceCenter(ServiceCenterType value) {
        this.serviceCenter = value;
    }

}
