//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.20 at 10:17:55 AM EDT 
//


package com.ups.xolt.codesamples.response.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PackageServiceOptionsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PackageServiceOptionsType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="COD" type="{}PackageCOD" minOccurs="0"/&gt;
 *         &lt;element name="SignatureRequired" type="{}CodeDescriptionType" minOccurs="0"/&gt;
 *         &lt;element name="ImportControl" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CommercialInvoiceRemoval" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="UPScarbonneutral" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="USPSPICNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ExchangeBased" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PackAndCollect" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PackageServiceOptionsType", propOrder = {
    "cod",
    "signatureRequired",
    "importControl",
    "commercialInvoiceRemoval",
    "upScarbonneutral",
    "uspspicNumber",
    "exchangeBased",
    "packAndCollect"
})
public class PackageServiceOptionsType {

    @XmlElement(name = "COD")
    protected PackageCOD cod;
    @XmlElement(name = "SignatureRequired")
    protected CodeDescriptionType signatureRequired;
    @XmlElement(name = "ImportControl")
    protected String importControl;
    @XmlElement(name = "CommercialInvoiceRemoval")
    protected String commercialInvoiceRemoval;
    @XmlElement(name = "UPScarbonneutral")
    protected String upScarbonneutral;
    @XmlElement(name = "USPSPICNumber")
    protected String uspspicNumber;
    @XmlElement(name = "ExchangeBased")
    protected String exchangeBased;
    @XmlElement(name = "PackAndCollect")
    protected String packAndCollect;

    /**
     * Gets the value of the cod property.
     * 
     * @return
     *     possible object is
     *     {@link PackageCOD }
     *     
     */
    public PackageCOD getCOD() {
        return cod;
    }

    /**
     * Sets the value of the cod property.
     * 
     * @param value
     *     allowed object is
     *     {@link PackageCOD }
     *     
     */
    public void setCOD(PackageCOD value) {
        this.cod = value;
    }

    /**
     * Gets the value of the signatureRequired property.
     * 
     * @return
     *     possible object is
     *     {@link CodeDescriptionType }
     *     
     */
    public CodeDescriptionType getSignatureRequired() {
        return signatureRequired;
    }

    /**
     * Sets the value of the signatureRequired property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeDescriptionType }
     *     
     */
    public void setSignatureRequired(CodeDescriptionType value) {
        this.signatureRequired = value;
    }

    /**
     * Gets the value of the importControl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImportControl() {
        return importControl;
    }

    /**
     * Sets the value of the importControl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImportControl(String value) {
        this.importControl = value;
    }

    /**
     * Gets the value of the commercialInvoiceRemoval property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommercialInvoiceRemoval() {
        return commercialInvoiceRemoval;
    }

    /**
     * Sets the value of the commercialInvoiceRemoval property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommercialInvoiceRemoval(String value) {
        this.commercialInvoiceRemoval = value;
    }

    /**
     * Gets the value of the upScarbonneutral property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUPScarbonneutral() {
        return upScarbonneutral;
    }

    /**
     * Sets the value of the upScarbonneutral property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUPScarbonneutral(String value) {
        this.upScarbonneutral = value;
    }

    /**
     * Gets the value of the uspspicNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUSPSPICNumber() {
        return uspspicNumber;
    }

    /**
     * Sets the value of the uspspicNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUSPSPICNumber(String value) {
        this.uspspicNumber = value;
    }

    /**
     * Gets the value of the exchangeBased property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExchangeBased() {
        return exchangeBased;
    }

    /**
     * Sets the value of the exchangeBased property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExchangeBased(String value) {
        this.exchangeBased = value;
    }

    /**
     * Gets the value of the packAndCollect property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPackAndCollect() {
        return packAndCollect;
    }

    /**
     * Sets the value of the packAndCollect property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPackAndCollect(String value) {
        this.packAndCollect = value;
    }

}
