LOCATION	Where am I
LOCATION	Tell me about {Havelock|location}
JUMP	jump to {Apaeronsk|location}
JUMP	go to {Apaeronsk|location}
JUMP	jump {Apaeronsk|location}
JUMP	move to {Apaeronsk|location}
SPACE	How much space do I have
SPACE	How much more can I carry
SPACE	How much can I carry
SPACE	What can I fit in
SPACE	space
MONEY	How much money do I have
MONEY	How much money
MONEY	bank account
MONEY	money
NEARBY	What's nearby
NEARBY	where can I go
NEARBY	nearby
NEARBY	neighborhood
RESET	reset
RESET	start over
DATE	date
DATE	time
DATE	what day is it
DATE	day
DATE	now
FORSALE	what's for sale
FORSALE	tell me about lot number {one|lotnum}
FORSALE	tell me about {one|lotnum}
FORSALE	what's on the dock
FORSALE	dock
FORSALE	dockside
BUY	buy lot number {one|lotnum}
BUY	buy {one|lotnum}
HOLD	hold
HOLD	what's in my hold
HOLD	what am I carrying
HOLD	what have I got
SELL	sell lot number {one|lotnum}
SELL	sell {one|lotnum}
PRICE	price lot number {one|lotnum}
PRICE	price {one|lotnum}
PRICE	what can I get for lot number {one|lotnum}
PRICE	what can I get for {one|lotnum}
